; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Downloads\MediaPoint\src\filters\BaseClasses\amextra.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	_IID_IAMFilterGraphCallback
CONST	SEGMENT
$SG81586 DB	'.', 00H, '.', 00H, '\', 00H, 'a', 00H, 'm', 00H, 'e', 00H
	DB	'x', 00H, 't', 00H, 'r', 00H, 'a', 00H, '.', 00H, 'c', 00H, 'p'
	DB	00H, 'p', 00H, 00H, 00H
	ORG $+2
$SG81587 DB	'(', 00H, '(', 00H, '(', 00H, 'H', 00H, 'R', 00H, 'E', 00H
	DB	'S', 00H, 'U', 00H, 'L', 00H, 'T', 00H, ')', 00H, '(', 00H, 'm'
	DB	00H, '_', 00H, 'p', 00H, 'F', 00H, 'i', 00H, 'l', 00H, 't', 00H
	DB	'e', 00H, 'r', 00H, '-', 00H, '>', 00H, 'G', 00H, 'e', 00H, 't'
	DB	00H, 'S', 00H, 't', 00H, 'a', 00H, 't', 00H, 'e', 00H, '(', 00H
	DB	'0', 00H, ',', 00H, ' ', 00H, '&', 00H, 'f', 00H, 's', 00H, ')'
	DB	00H, ')', 00H, ')', 00H, ' ', 00H, '>', 00H, '=', 00H, ' ', 00H
	DB	'0', 00H, ')', 00H, 00H, 00H
$SG81607 DB	'.', 00H, '.', 00H, '\', 00H, 'a', 00H, 'm', 00H, 'e', 00H
	DB	'x', 00H, 't', 00H, 'r', 00H, 'a', 00H, '.', 00H, 'c', 00H, 'p'
	DB	00H, 'p', 00H, 00H, 00H
	ORG $+2
$SG81608 DB	'm', 00H, '_', 00H, 'b', 00H, 'A', 00H, 't', 00H, 'E', 00H
	DB	'n', 00H, 'd', 00H, 'O', 00H, 'f', 00H, 'S', 00H, 't', 00H, 'r'
	DB	00H, 'e', 00H, 'a', 00H, 'm', 00H, 00H, 00H
CONST	ENDS
;	COMDAT _IID_IAMFilterGraphCallback
CONST	SEGMENT
_IID_IAMFilterGraphCallback DD 056a868fdH
	DW	0ad4H
	DW	011ceH
	DB	0b0H
	DB	0a3H
	DB	00H
	DB	020H
	DB	0afH
	DB	0bH
	DB	0a7H
	DB	070H
CONST	ENDS
PUBLIC	??_7CRenderedInputPin@@6B@			; CRenderedInputPin::`vftable'
PUBLIC	??_7CRenderedInputPin@@6BIQualityControl@@@	; CRenderedInputPin::`vftable'
PUBLIC	??_7CRenderedInputPin@@6BIPin@@@		; CRenderedInputPin::`vftable'
PUBLIC	??_7CRenderedInputPin@@6BCUnknown@@@		; CRenderedInputPin::`vftable'
PUBLIC	??0CRenderedInputPin@@QAE@PA_WPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z ; CRenderedInputPin::CRenderedInputPin
PUBLIC	??_R4CRenderedInputPin@@6BCUnknown@@@		; CRenderedInputPin::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCRenderedInputPin@@@8			; CRenderedInputPin `RTTI Type Descriptor'
PUBLIC	??_R3CRenderedInputPin@@8			; CRenderedInputPin::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CRenderedInputPin@@8			; CRenderedInputPin::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CRenderedInputPin@@8		; CRenderedInputPin::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@CBaseInputPin@@8			; CBaseInputPin::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCBaseInputPin@@@8			; CBaseInputPin `RTTI Type Descriptor'
PUBLIC	??_R3CBaseInputPin@@8				; CBaseInputPin::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CBaseInputPin@@8				; CBaseInputPin::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CBasePin@@8			; CBasePin::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCBasePin@@@8				; CBasePin `RTTI Type Descriptor'
PUBLIC	??_R3CBasePin@@8				; CBasePin::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CBasePin@@8				; CBasePin::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CUnknown@@8			; CUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCUnknown@@@8				; CUnknown `RTTI Type Descriptor'
PUBLIC	??_R3CUnknown@@8				; CUnknown::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CUnknown@@8				; CUnknown::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@INonDelegatingUnknown@@8		; INonDelegatingUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AUINonDelegatingUnknown@@@8		; INonDelegatingUnknown `RTTI Type Descriptor'
PUBLIC	??_R3INonDelegatingUnknown@@8			; INonDelegatingUnknown::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2INonDelegatingUnknown@@8			; INonDelegatingUnknown::`RTTI Base Class Array'
PUBLIC	??_R13?0A@EA@CBaseObject@@8			; CBaseObject::`RTTI Base Class Descriptor at (4,-1,0,64)'
PUBLIC	??_R0?AVCBaseObject@@@8				; CBaseObject `RTTI Type Descriptor'
PUBLIC	??_R3CBaseObject@@8				; CBaseObject::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CBaseObject@@8				; CBaseObject::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CBaseObject@@8			; CBaseObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1BA@?0A@EA@IPin@@8				; IPin::`RTTI Base Class Descriptor at (16,-1,0,64)'
PUBLIC	??_R0?AUIPin@@@8				; IPin `RTTI Type Descriptor'
PUBLIC	??_R3IPin@@8					; IPin::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IPin@@8					; IPin::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@IPin@@8				; IPin::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@IUnknown@@8			; IUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AUIUnknown@@@8				; IUnknown `RTTI Type Descriptor'
PUBLIC	??_R3IUnknown@@8				; IUnknown::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IUnknown@@8				; IUnknown::`RTTI Base Class Array'
PUBLIC	??_R1BA@?0A@EC@IUnknown@@8			; IUnknown::`RTTI Base Class Descriptor at (16,-1,0,66)'
PUBLIC	??_R1BE@?0A@EA@IQualityControl@@8		; IQualityControl::`RTTI Base Class Descriptor at (20,-1,0,64)'
PUBLIC	??_R0?AUIQualityControl@@@8			; IQualityControl `RTTI Type Descriptor'
PUBLIC	??_R3IQualityControl@@8				; IQualityControl::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IQualityControl@@8				; IQualityControl::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@IQualityControl@@8		; IQualityControl::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1BE@?0A@EC@IUnknown@@8			; IUnknown::`RTTI Base Class Descriptor at (20,-1,0,66)'
PUBLIC	??_R1KA@?0A@EA@IMemInputPin@@8			; IMemInputPin::`RTTI Base Class Descriptor at (160,-1,0,64)'
PUBLIC	??_R0?AUIMemInputPin@@@8			; IMemInputPin `RTTI Type Descriptor'
PUBLIC	??_R3IMemInputPin@@8				; IMemInputPin::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IMemInputPin@@8				; IMemInputPin::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@IMemInputPin@@8			; IMemInputPin::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1KA@?0A@EC@IUnknown@@8			; IUnknown::`RTTI Base Class Descriptor at (160,-1,0,66)'
PUBLIC	?Active@CRenderedInputPin@@UAEJXZ		; CRenderedInputPin::Active
PUBLIC	?Run@CRenderedInputPin@@UAEJ_J@Z		; CRenderedInputPin::Run
PUBLIC	??_R4CRenderedInputPin@@6BIPin@@@		; CRenderedInputPin::`RTTI Complete Object Locator'
PUBLIC	?QueryInterface@CBaseInputPin@@UAGJABU_GUID@@PAPAX@Z ; CBaseInputPin::QueryInterface
PUBLIC	?AddRef@CBaseInputPin@@UAGKXZ			; CBaseInputPin::AddRef
PUBLIC	?Release@CBaseInputPin@@UAGKXZ			; CBaseInputPin::Release
PUBLIC	?QueryInternalConnections@CBasePin@@UAGJPAPAUIPin@@PAK@Z ; CBasePin::QueryInternalConnections
PUBLIC	?EndOfStream@CRenderedInputPin@@UAGJXZ		; CRenderedInputPin::EndOfStream
PUBLIC	?EndFlush@CRenderedInputPin@@UAGJXZ		; CRenderedInputPin::EndFlush
PUBLIC	??_R4CRenderedInputPin@@6BIQualityControl@@@	; CRenderedInputPin::`RTTI Complete Object Locator'
PUBLIC	?QueryInterface@CBaseInputPin@@W3AGJABU_GUID@@PAPAX@Z ; [thunk]:CBaseInputPin::QueryInterface`adjustor{4}'
PUBLIC	?AddRef@CBaseInputPin@@W3AGKXZ			; [thunk]:CBaseInputPin::AddRef`adjustor{4}'
PUBLIC	?Release@CBaseInputPin@@W3AGKXZ			; [thunk]:CBaseInputPin::Release`adjustor{4}'
PUBLIC	??_R4CRenderedInputPin@@6B@			; CRenderedInputPin::`RTTI Complete Object Locator'
PUBLIC	?QueryInterface@CBaseInputPin@@WJA@AGJABU_GUID@@PAPAX@Z ; [thunk]:CBaseInputPin::QueryInterface`adjustor{144}'
PUBLIC	?AddRef@CBaseInputPin@@WJA@AGKXZ		; [thunk]:CBaseInputPin::AddRef`adjustor{144}'
PUBLIC	?Release@CBaseInputPin@@WJA@AGKXZ		; [thunk]:CBaseInputPin::Release`adjustor{144}'
EXTRN	??0CBaseInputPin@@QAE@PA_WPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z:PROC ; CBaseInputPin::CBaseInputPin
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	?NonDelegatingQueryInterface@CBaseInputPin@@UAGJABU_GUID@@PAPAX@Z:PROC ; CBaseInputPin::NonDelegatingQueryInterface
EXTRN	?NonDelegatingAddRef@CBasePin@@UAGKXZ:PROC	; CBasePin::NonDelegatingAddRef
EXTRN	?NonDelegatingRelease@CBasePin@@UAGKXZ:PROC	; CBasePin::NonDelegatingRelease
EXTRN	??_ECRenderedInputPin@@UAEPAXI@Z:PROC		; CRenderedInputPin::`vector deleting destructor'
EXTRN	?GetMediaTypeVersion@CBasePin@@UAEJXZ:PROC	; CBasePin::GetMediaTypeVersion
EXTRN	?Inactive@CBaseInputPin@@UAEJXZ:PROC		; CBaseInputPin::Inactive
EXTRN	__purecall:PROC
EXTRN	?SetMediaType@CBasePin@@UAEJPBVCMediaType@@@Z:PROC ; CBasePin::SetMediaType
EXTRN	?CheckConnect@CBasePin@@UAEJPAUIPin@@@Z:PROC	; CBasePin::CheckConnect
EXTRN	?BreakConnect@CBaseInputPin@@UAEJXZ:PROC	; CBaseInputPin::BreakConnect
EXTRN	?CompleteConnect@CBasePin@@UAEJPAUIPin@@@Z:PROC	; CBasePin::CompleteConnect
EXTRN	?GetMediaType@CBasePin@@UAEJHPAVCMediaType@@@Z:PROC ; CBasePin::GetMediaType
EXTRN	?CheckStreaming@CBaseInputPin@@UAEJXZ:PROC	; CBaseInputPin::CheckStreaming
EXTRN	?Connect@CBasePin@@UAGJPAUIPin@@PBU_AMMediaType@@@Z:PROC ; CBasePin::Connect
EXTRN	?ReceiveConnection@CBasePin@@UAGJPAUIPin@@PBU_AMMediaType@@@Z:PROC ; CBasePin::ReceiveConnection
EXTRN	?Disconnect@CBasePin@@UAGJXZ:PROC		; CBasePin::Disconnect
EXTRN	?ConnectedTo@CBasePin@@UAGJPAPAUIPin@@@Z:PROC	; CBasePin::ConnectedTo
EXTRN	?ConnectionMediaType@CBasePin@@UAGJPAU_AMMediaType@@@Z:PROC ; CBasePin::ConnectionMediaType
EXTRN	?QueryPinInfo@CBasePin@@UAGJPAU_PinInfo@@@Z:PROC ; CBasePin::QueryPinInfo
EXTRN	?QueryDirection@CBasePin@@UAGJPAW4_PinDirection@@@Z:PROC ; CBasePin::QueryDirection
EXTRN	?QueryId@CBasePin@@UAGJPAPA_W@Z:PROC		; CBasePin::QueryId
EXTRN	?QueryAccept@CBasePin@@UAGJPBU_AMMediaType@@@Z:PROC ; CBasePin::QueryAccept
EXTRN	?EnumMediaTypes@CBasePin@@UAGJPAPAUIEnumMediaTypes@@@Z:PROC ; CBasePin::EnumMediaTypes
EXTRN	?BeginFlush@CBaseInputPin@@UAGJXZ:PROC		; CBaseInputPin::BeginFlush
EXTRN	?NewSegment@CBasePin@@UAGJ_J0N@Z:PROC		; CBasePin::NewSegment
EXTRN	?Notify@CBaseInputPin@@UAGJPAUIBaseFilter@@UtagQuality@@@Z:PROC ; CBaseInputPin::Notify
EXTRN	?SetSink@CBasePin@@UAGJPAUIQualityControl@@@Z:PROC ; CBasePin::SetSink
EXTRN	?GetAllocator@CBaseInputPin@@UAGJPAPAUIMemAllocator@@@Z:PROC ; CBaseInputPin::GetAllocator
EXTRN	?NotifyAllocator@CBaseInputPin@@UAGJPAUIMemAllocator@@H@Z:PROC ; CBaseInputPin::NotifyAllocator
EXTRN	?GetAllocatorRequirements@CBaseInputPin@@UAGJPAU_AllocatorProperties@@@Z:PROC ; CBaseInputPin::GetAllocatorRequirements
EXTRN	?Receive@CBaseInputPin@@UAGJPAUIMediaSample@@@Z:PROC ; CBaseInputPin::Receive
EXTRN	?ReceiveMultiple@CBaseInputPin@@UAGJPAPAUIMediaSample@@JPAJ@Z:PROC ; CBaseInputPin::ReceiveMultiple
EXTRN	?ReceiveCanBlock@CBaseInputPin@@UAGJXZ:PROC	; CBaseInputPin::ReceiveCanBlock
;	COMDAT ??_R4CRenderedInputPin@@6B@
; File c:\downloads\mediapoint\src\filters\baseclasses\amextra.cpp
rdata$r	SEGMENT
??_R4CRenderedInputPin@@6B@ DD 00H			; CRenderedInputPin::`RTTI Complete Object Locator'
	DD	0a0H
	DD	00H
	DD	FLAT:??_R0?AVCRenderedInputPin@@@8
	DD	FLAT:??_R3CRenderedInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R4CRenderedInputPin@@6BIQualityControl@@@
rdata$r	SEGMENT
??_R4CRenderedInputPin@@6BIQualityControl@@@ DD 00H	; CRenderedInputPin::`RTTI Complete Object Locator'
	DD	014H
	DD	00H
	DD	FLAT:??_R0?AVCRenderedInputPin@@@8
	DD	FLAT:??_R3CRenderedInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R4CRenderedInputPin@@6BIPin@@@
rdata$r	SEGMENT
??_R4CRenderedInputPin@@6BIPin@@@ DD 00H		; CRenderedInputPin::`RTTI Complete Object Locator'
	DD	010H
	DD	00H
	DD	FLAT:??_R0?AVCRenderedInputPin@@@8
	DD	FLAT:??_R3CRenderedInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R1KA@?0A@EC@IUnknown@@8
rdata$r	SEGMENT
??_R1KA@?0A@EC@IUnknown@@8 DD FLAT:??_R0?AUIUnknown@@@8	; IUnknown::`RTTI Base Class Descriptor at (160,-1,0,66)'
	DD	00H
	DD	0a0H
	DD	0ffffffffH
	DD	00H
	DD	042H
	DD	FLAT:??_R3IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@IMemInputPin@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IMemInputPin@@8 DD FLAT:??_R0?AUIMemInputPin@@@8 ; IMemInputPin::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IMemInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R2IMemInputPin@@8
rdata$r	SEGMENT
??_R2IMemInputPin@@8 DD FLAT:??_R1A@?0A@EA@IMemInputPin@@8 ; IMemInputPin::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R3IMemInputPin@@8
rdata$r	SEGMENT
??_R3IMemInputPin@@8 DD 00H				; IMemInputPin::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2IMemInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIMemInputPin@@@8
_DATA	SEGMENT
??_R0?AUIMemInputPin@@@8 DD FLAT:??_7type_info@@6B@	; IMemInputPin `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIMemInputPin@@', 00H
_DATA	ENDS
;	COMDAT ??_R1KA@?0A@EA@IMemInputPin@@8
rdata$r	SEGMENT
??_R1KA@?0A@EA@IMemInputPin@@8 DD FLAT:??_R0?AUIMemInputPin@@@8 ; IMemInputPin::`RTTI Base Class Descriptor at (160,-1,0,64)'
	DD	01H
	DD	0a0H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IMemInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R1BE@?0A@EC@IUnknown@@8
rdata$r	SEGMENT
??_R1BE@?0A@EC@IUnknown@@8 DD FLAT:??_R0?AUIUnknown@@@8	; IUnknown::`RTTI Base Class Descriptor at (20,-1,0,66)'
	DD	00H
	DD	014H
	DD	0ffffffffH
	DD	00H
	DD	042H
	DD	FLAT:??_R3IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@IQualityControl@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IQualityControl@@8 DD FLAT:??_R0?AUIQualityControl@@@8 ; IQualityControl::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IQualityControl@@8
rdata$r	ENDS
;	COMDAT ??_R2IQualityControl@@8
rdata$r	SEGMENT
??_R2IQualityControl@@8 DD FLAT:??_R1A@?0A@EA@IQualityControl@@8 ; IQualityControl::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R3IQualityControl@@8
rdata$r	SEGMENT
??_R3IQualityControl@@8 DD 00H				; IQualityControl::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2IQualityControl@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIQualityControl@@@8
_DATA	SEGMENT
??_R0?AUIQualityControl@@@8 DD FLAT:??_7type_info@@6B@	; IQualityControl `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIQualityControl@@', 00H
_DATA	ENDS
;	COMDAT ??_R1BE@?0A@EA@IQualityControl@@8
rdata$r	SEGMENT
??_R1BE@?0A@EA@IQualityControl@@8 DD FLAT:??_R0?AUIQualityControl@@@8 ; IQualityControl::`RTTI Base Class Descriptor at (20,-1,0,64)'
	DD	01H
	DD	014H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IQualityControl@@8
rdata$r	ENDS
;	COMDAT ??_R1BA@?0A@EC@IUnknown@@8
rdata$r	SEGMENT
??_R1BA@?0A@EC@IUnknown@@8 DD FLAT:??_R0?AUIUnknown@@@8	; IUnknown::`RTTI Base Class Descriptor at (16,-1,0,66)'
	DD	00H
	DD	010H
	DD	0ffffffffH
	DD	00H
	DD	042H
	DD	FLAT:??_R3IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R2IUnknown@@8
rdata$r	SEGMENT
??_R2IUnknown@@8 DD FLAT:??_R1A@?0A@EA@IUnknown@@8	; IUnknown::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3IUnknown@@8
rdata$r	SEGMENT
??_R3IUnknown@@8 DD 00H					; IUnknown::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIUnknown@@@8
_DATA	SEGMENT
??_R0?AUIUnknown@@@8 DD FLAT:??_7type_info@@6B@		; IUnknown `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIUnknown@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@IUnknown@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IUnknown@@8 DD FLAT:??_R0?AUIUnknown@@@8	; IUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@IPin@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IPin@@8 DD FLAT:??_R0?AUIPin@@@8		; IPin::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IPin@@8
rdata$r	ENDS
;	COMDAT ??_R2IPin@@8
rdata$r	SEGMENT
??_R2IPin@@8 DD	FLAT:??_R1A@?0A@EA@IPin@@8		; IPin::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R3IPin@@8
rdata$r	SEGMENT
??_R3IPin@@8 DD	00H					; IPin::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2IPin@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIPin@@@8
_DATA	SEGMENT
??_R0?AUIPin@@@8 DD FLAT:??_7type_info@@6B@		; IPin `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIPin@@', 00H
_DATA	ENDS
;	COMDAT ??_R1BA@?0A@EA@IPin@@8
rdata$r	SEGMENT
??_R1BA@?0A@EA@IPin@@8 DD FLAT:??_R0?AUIPin@@@8		; IPin::`RTTI Base Class Descriptor at (16,-1,0,64)'
	DD	01H
	DD	010H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IPin@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CBaseObject@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CBaseObject@@8 DD FLAT:??_R0?AVCBaseObject@@@8 ; CBaseObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CBaseObject@@8
rdata$r	ENDS
;	COMDAT ??_R2CBaseObject@@8
rdata$r	SEGMENT
??_R2CBaseObject@@8 DD FLAT:??_R1A@?0A@EA@CBaseObject@@8 ; CBaseObject::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3CBaseObject@@8
rdata$r	SEGMENT
??_R3CBaseObject@@8 DD 00H				; CBaseObject::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2CBaseObject@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCBaseObject@@@8
_DATA	SEGMENT
??_R0?AVCBaseObject@@@8 DD FLAT:??_7type_info@@6B@	; CBaseObject `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCBaseObject@@', 00H
_DATA	ENDS
;	COMDAT ??_R13?0A@EA@CBaseObject@@8
rdata$r	SEGMENT
??_R13?0A@EA@CBaseObject@@8 DD FLAT:??_R0?AVCBaseObject@@@8 ; CBaseObject::`RTTI Base Class Descriptor at (4,-1,0,64)'
	DD	00H
	DD	04H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CBaseObject@@8
rdata$r	ENDS
;	COMDAT ??_R2INonDelegatingUnknown@@8
rdata$r	SEGMENT
??_R2INonDelegatingUnknown@@8 DD FLAT:??_R1A@?0A@EA@INonDelegatingUnknown@@8 ; INonDelegatingUnknown::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3INonDelegatingUnknown@@8
rdata$r	SEGMENT
??_R3INonDelegatingUnknown@@8 DD 00H			; INonDelegatingUnknown::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2INonDelegatingUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUINonDelegatingUnknown@@@8
_DATA	SEGMENT
??_R0?AUINonDelegatingUnknown@@@8 DD FLAT:??_7type_info@@6B@ ; INonDelegatingUnknown `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUINonDelegatingUnknown@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@INonDelegatingUnknown@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@INonDelegatingUnknown@@8 DD FLAT:??_R0?AUINonDelegatingUnknown@@@8 ; INonDelegatingUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3INonDelegatingUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R2CUnknown@@8
rdata$r	SEGMENT
??_R2CUnknown@@8 DD FLAT:??_R1A@?0A@EA@CUnknown@@8	; CUnknown::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@INonDelegatingUnknown@@8
	DD	FLAT:??_R13?0A@EA@CBaseObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CUnknown@@8
rdata$r	SEGMENT
??_R3CUnknown@@8 DD 00H					; CUnknown::`RTTI Class Hierarchy Descriptor'
	DD	01H
	DD	03H
	DD	FLAT:??_R2CUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCUnknown@@@8
_DATA	SEGMENT
??_R0?AVCUnknown@@@8 DD FLAT:??_7type_info@@6B@		; CUnknown `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCUnknown@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@CUnknown@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CUnknown@@8 DD FLAT:??_R0?AVCUnknown@@@8	; CUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R2CBasePin@@8
rdata$r	SEGMENT
??_R2CBasePin@@8 DD FLAT:??_R1A@?0A@EA@CBasePin@@8	; CBasePin::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CUnknown@@8
	DD	FLAT:??_R1A@?0A@EA@INonDelegatingUnknown@@8
	DD	FLAT:??_R13?0A@EA@CBaseObject@@8
	DD	FLAT:??_R1BA@?0A@EA@IPin@@8
	DD	FLAT:??_R1BA@?0A@EC@IUnknown@@8
	DD	FLAT:??_R1BE@?0A@EA@IQualityControl@@8
	DD	FLAT:??_R1BE@?0A@EC@IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R3CBasePin@@8
rdata$r	SEGMENT
??_R3CBasePin@@8 DD 00H					; CBasePin::`RTTI Class Hierarchy Descriptor'
	DD	05H
	DD	08H
	DD	FLAT:??_R2CBasePin@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCBasePin@@@8
_DATA	SEGMENT
??_R0?AVCBasePin@@@8 DD FLAT:??_7type_info@@6B@		; CBasePin `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCBasePin@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@CBasePin@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CBasePin@@8 DD FLAT:??_R0?AVCBasePin@@@8	; CBasePin::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	07H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CBasePin@@8
rdata$r	ENDS
;	COMDAT ??_R2CBaseInputPin@@8
rdata$r	SEGMENT
??_R2CBaseInputPin@@8 DD FLAT:??_R1A@?0A@EA@CBaseInputPin@@8 ; CBaseInputPin::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CBasePin@@8
	DD	FLAT:??_R1A@?0A@EA@CUnknown@@8
	DD	FLAT:??_R1A@?0A@EA@INonDelegatingUnknown@@8
	DD	FLAT:??_R13?0A@EA@CBaseObject@@8
	DD	FLAT:??_R1BA@?0A@EA@IPin@@8
	DD	FLAT:??_R1BA@?0A@EC@IUnknown@@8
	DD	FLAT:??_R1BE@?0A@EA@IQualityControl@@8
	DD	FLAT:??_R1BE@?0A@EC@IUnknown@@8
	DD	FLAT:??_R1KA@?0A@EA@IMemInputPin@@8
	DD	FLAT:??_R1KA@?0A@EC@IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R3CBaseInputPin@@8
rdata$r	SEGMENT
??_R3CBaseInputPin@@8 DD 00H				; CBaseInputPin::`RTTI Class Hierarchy Descriptor'
	DD	05H
	DD	0bH
	DD	FLAT:??_R2CBaseInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCBaseInputPin@@@8
_DATA	SEGMENT
??_R0?AVCBaseInputPin@@@8 DD FLAT:??_7type_info@@6B@	; CBaseInputPin `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCBaseInputPin@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@CBaseInputPin@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CBaseInputPin@@8 DD FLAT:??_R0?AVCBaseInputPin@@@8 ; CBaseInputPin::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	0aH
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CBaseInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CRenderedInputPin@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CRenderedInputPin@@8 DD FLAT:??_R0?AVCRenderedInputPin@@@8 ; CRenderedInputPin::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	0bH
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CRenderedInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R2CRenderedInputPin@@8
rdata$r	SEGMENT
??_R2CRenderedInputPin@@8 DD FLAT:??_R1A@?0A@EA@CRenderedInputPin@@8 ; CRenderedInputPin::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CBaseInputPin@@8
	DD	FLAT:??_R1A@?0A@EA@CBasePin@@8
	DD	FLAT:??_R1A@?0A@EA@CUnknown@@8
	DD	FLAT:??_R1A@?0A@EA@INonDelegatingUnknown@@8
	DD	FLAT:??_R13?0A@EA@CBaseObject@@8
	DD	FLAT:??_R1BA@?0A@EA@IPin@@8
	DD	FLAT:??_R1BA@?0A@EC@IUnknown@@8
	DD	FLAT:??_R1BE@?0A@EA@IQualityControl@@8
	DD	FLAT:??_R1BE@?0A@EC@IUnknown@@8
	DD	FLAT:??_R1KA@?0A@EA@IMemInputPin@@8
	DD	FLAT:??_R1KA@?0A@EC@IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R3CRenderedInputPin@@8
rdata$r	SEGMENT
??_R3CRenderedInputPin@@8 DD 00H			; CRenderedInputPin::`RTTI Class Hierarchy Descriptor'
	DD	01H
	DD	0cH
	DD	FLAT:??_R2CRenderedInputPin@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCRenderedInputPin@@@8
_DATA	SEGMENT
??_R0?AVCRenderedInputPin@@@8 DD FLAT:??_7type_info@@6B@ ; CRenderedInputPin `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCRenderedInputPin@@', 00H
_DATA	ENDS
;	COMDAT ??_R4CRenderedInputPin@@6BCUnknown@@@
rdata$r	SEGMENT
??_R4CRenderedInputPin@@6BCUnknown@@@ DD 00H		; CRenderedInputPin::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCRenderedInputPin@@@8
	DD	FLAT:??_R3CRenderedInputPin@@8
rdata$r	ENDS
;	COMDAT ??_7CRenderedInputPin@@6B@
CONST	SEGMENT
??_7CRenderedInputPin@@6B@ DD FLAT:??_R4CRenderedInputPin@@6B@ ; CRenderedInputPin::`vftable'
	DD	FLAT:?QueryInterface@CBaseInputPin@@WJA@AGJABU_GUID@@PAPAX@Z
	DD	FLAT:?AddRef@CBaseInputPin@@WJA@AGKXZ
	DD	FLAT:?Release@CBaseInputPin@@WJA@AGKXZ
	DD	FLAT:?GetAllocator@CBaseInputPin@@UAGJPAPAUIMemAllocator@@@Z
	DD	FLAT:?NotifyAllocator@CBaseInputPin@@UAGJPAUIMemAllocator@@H@Z
	DD	FLAT:?GetAllocatorRequirements@CBaseInputPin@@UAGJPAU_AllocatorProperties@@@Z
	DD	FLAT:?Receive@CBaseInputPin@@UAGJPAUIMediaSample@@@Z
	DD	FLAT:?ReceiveMultiple@CBaseInputPin@@UAGJPAPAUIMediaSample@@JPAJ@Z
	DD	FLAT:?ReceiveCanBlock@CBaseInputPin@@UAGJXZ
CONST	ENDS
;	COMDAT ??_7CRenderedInputPin@@6BIQualityControl@@@
CONST	SEGMENT
??_7CRenderedInputPin@@6BIQualityControl@@@ DD FLAT:??_R4CRenderedInputPin@@6BIQualityControl@@@ ; CRenderedInputPin::`vftable'
	DD	FLAT:?QueryInterface@CBaseInputPin@@W3AGJABU_GUID@@PAPAX@Z
	DD	FLAT:?AddRef@CBaseInputPin@@W3AGKXZ
	DD	FLAT:?Release@CBaseInputPin@@W3AGKXZ
	DD	FLAT:?Notify@CBaseInputPin@@UAGJPAUIBaseFilter@@UtagQuality@@@Z
	DD	FLAT:?SetSink@CBasePin@@UAGJPAUIQualityControl@@@Z
CONST	ENDS
;	COMDAT ??_7CRenderedInputPin@@6BIPin@@@
CONST	SEGMENT
??_7CRenderedInputPin@@6BIPin@@@ DD FLAT:??_R4CRenderedInputPin@@6BIPin@@@ ; CRenderedInputPin::`vftable'
	DD	FLAT:?QueryInterface@CBaseInputPin@@UAGJABU_GUID@@PAPAX@Z
	DD	FLAT:?AddRef@CBaseInputPin@@UAGKXZ
	DD	FLAT:?Release@CBaseInputPin@@UAGKXZ
	DD	FLAT:?Connect@CBasePin@@UAGJPAUIPin@@PBU_AMMediaType@@@Z
	DD	FLAT:?ReceiveConnection@CBasePin@@UAGJPAUIPin@@PBU_AMMediaType@@@Z
	DD	FLAT:?Disconnect@CBasePin@@UAGJXZ
	DD	FLAT:?ConnectedTo@CBasePin@@UAGJPAPAUIPin@@@Z
	DD	FLAT:?ConnectionMediaType@CBasePin@@UAGJPAU_AMMediaType@@@Z
	DD	FLAT:?QueryPinInfo@CBasePin@@UAGJPAU_PinInfo@@@Z
	DD	FLAT:?QueryDirection@CBasePin@@UAGJPAW4_PinDirection@@@Z
	DD	FLAT:?QueryId@CBasePin@@UAGJPAPA_W@Z
	DD	FLAT:?QueryAccept@CBasePin@@UAGJPBU_AMMediaType@@@Z
	DD	FLAT:?EnumMediaTypes@CBasePin@@UAGJPAPAUIEnumMediaTypes@@@Z
	DD	FLAT:?QueryInternalConnections@CBasePin@@UAGJPAPAUIPin@@PAK@Z
	DD	FLAT:?EndOfStream@CRenderedInputPin@@UAGJXZ
	DD	FLAT:?BeginFlush@CBaseInputPin@@UAGJXZ
	DD	FLAT:?EndFlush@CRenderedInputPin@@UAGJXZ
	DD	FLAT:?NewSegment@CBasePin@@UAGJ_J0N@Z
CONST	ENDS
;	COMDAT ??_7CRenderedInputPin@@6BCUnknown@@@
CONST	SEGMENT
??_7CRenderedInputPin@@6BCUnknown@@@ DD FLAT:??_R4CRenderedInputPin@@6BCUnknown@@@ ; CRenderedInputPin::`vftable'
	DD	FLAT:?NonDelegatingQueryInterface@CBaseInputPin@@UAGJABU_GUID@@PAPAX@Z
	DD	FLAT:?NonDelegatingAddRef@CBasePin@@UAGKXZ
	DD	FLAT:?NonDelegatingRelease@CBasePin@@UAGKXZ
	DD	FLAT:??_ECRenderedInputPin@@UAEPAXI@Z
	DD	FLAT:?GetMediaTypeVersion@CBasePin@@UAEJXZ
	DD	FLAT:?Active@CRenderedInputPin@@UAEJXZ
	DD	FLAT:?Inactive@CBaseInputPin@@UAEJXZ
	DD	FLAT:?Run@CRenderedInputPin@@UAEJ_J@Z
	DD	FLAT:__purecall
	DD	FLAT:?SetMediaType@CBasePin@@UAEJPBVCMediaType@@@Z
	DD	FLAT:?CheckConnect@CBasePin@@UAEJPAUIPin@@@Z
	DD	FLAT:?BreakConnect@CBaseInputPin@@UAEJXZ
	DD	FLAT:?CompleteConnect@CBasePin@@UAEJPAUIPin@@@Z
	DD	FLAT:?GetMediaType@CBasePin@@UAEJHPAVCMediaType@@@Z
	DD	FLAT:?CheckStreaming@CBaseInputPin@@UAEJXZ
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu
rtc$IMZ	ENDS
;	COMDAT ??0CRenderedInputPin@@QAE@PA_WPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_pObjectName$ = 8					; size = 4
_pFilter$ = 12						; size = 4
_pLock$ = 16						; size = 4
_phr$ = 20						; size = 4
_pName$ = 24						; size = 4
??0CRenderedInputPin@@QAE@PA_WPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z PROC ; CRenderedInputPin::CRenderedInputPin, COMDAT
; _this$ = ecx
; Line 29
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _pName$[ebp]
	push	eax
	mov	ecx, DWORD PTR _phr$[ebp]
	push	ecx
	mov	edx, DWORD PTR _pLock$[ebp]
	push	edx
	mov	eax, DWORD PTR _pFilter$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pObjectName$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0CBaseInputPin@@QAE@PA_WPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z ; CBaseInputPin::CBaseInputPin
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx], OFFSET ??_7CRenderedInputPin@@6BCUnknown@@@
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+16], OFFSET ??_7CRenderedInputPin@@6BIPin@@@
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+20], OFFSET ??_7CRenderedInputPin@@6BIQualityControl@@@
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+160], OFFSET ??_7CRenderedInputPin@@6B@
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+224], 0
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+228], 0
; Line 30
	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	20					; 00000014H
??0CRenderedInputPin@@QAE@PA_WPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z ENDP ; CRenderedInputPin::CRenderedInputPin
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?QueryInternalConnections@CBasePin@@UAGJPAPAUIPin@@PAK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_apPin$ = 12						; size = 4
_nPin$ = 16						; size = 4
?QueryInternalConnections@CBasePin@@UAGJPAPAUIPin@@PAK@Z PROC ; CBasePin::QueryInternalConnections, COMDAT
; File c:\downloads\mediapoint\src\filters\baseclasses\amfilter.h
; Line 472
	push	ebp
	mov	ebp, esp
	mov	eax, -2147467263			; 80004001H
	pop	ebp
	ret	12					; 0000000cH
?QueryInternalConnections@CBasePin@@UAGJPAPAUIPin@@PAK@Z ENDP ; CBasePin::QueryInternalConnections
_TEXT	ENDS
PUBLIC	?GetOwner@CUnknown@@QBEPAUIUnknown@@XZ		; CUnknown::GetOwner
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?QueryInterface@CBaseInputPin@@UAGJABU_GUID@@PAPAX@Z
_TEXT	SEGMENT
tv72 = -4						; size = 4
_this$ = 8						; size = 4
_riid$ = 12						; size = 4
_ppv$ = 16						; size = 4
?QueryInterface@CBaseInputPin@@UAGJABU_GUID@@PAPAX@Z PROC ; CBaseInputPin::QueryInterface, COMDAT
; Line 857
	push	ebp
	mov	ebp, esp
	push	ecx
	push	esi
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	ecx, DWORD PTR _this$[ebp]
	sub	ecx, 16					; 00000010H
	call	?GetOwner@CUnknown@@QBEPAUIUnknown@@XZ	; CUnknown::GetOwner
	mov	DWORD PTR tv72[ebp], eax
	mov	esi, esp
	mov	eax, DWORD PTR _ppv$[ebp]
	push	eax
	mov	ecx, DWORD PTR _riid$[ebp]
	push	ecx
	mov	edx, DWORD PTR tv72[ebp]
	push	edx
	mov	eax, DWORD PTR tv72[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
	pop	esi
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?QueryInterface@CBaseInputPin@@UAGJABU_GUID@@PAPAX@Z ENDP ; CBaseInputPin::QueryInterface
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?GetOwner@CUnknown@@QBEPAUIUnknown@@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?GetOwner@CUnknown@@QBEPAUIUnknown@@XZ PROC		; CUnknown::GetOwner, COMDAT
; _this$ = ecx
; File c:\downloads\mediapoint\src\filters\baseclasses\combase.h
; Line 224
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
; Line 225
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]
; Line 226
	mov	esp, ebp
	pop	ebp
	ret	0
?GetOwner@CUnknown@@QBEPAUIUnknown@@XZ ENDP		; CUnknown::GetOwner
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?AddRef@CBaseInputPin@@UAGKXZ
_TEXT	SEGMENT
tv72 = -4						; size = 4
_this$ = 8						; size = 4
?AddRef@CBaseInputPin@@UAGKXZ PROC			; CBaseInputPin::AddRef, COMDAT
; File c:\downloads\mediapoint\src\filters\baseclasses\amfilter.h
; Line 857
	push	ebp
	mov	ebp, esp
	push	ecx
	push	esi
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	ecx, DWORD PTR _this$[ebp]
	sub	ecx, 16					; 00000010H
	call	?GetOwner@CUnknown@@QBEPAUIUnknown@@XZ	; CUnknown::GetOwner
	mov	DWORD PTR tv72[ebp], eax
	mov	eax, DWORD PTR tv72[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	esi, esp
	mov	edx, DWORD PTR tv72[ebp]
	push	edx
	mov	eax, DWORD PTR [ecx+4]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	pop	esi
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?AddRef@CBaseInputPin@@UAGKXZ ENDP			; CBaseInputPin::AddRef
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?Release@CBaseInputPin@@UAGKXZ
_TEXT	SEGMENT
tv72 = -4						; size = 4
_this$ = 8						; size = 4
?Release@CBaseInputPin@@UAGKXZ PROC			; CBaseInputPin::Release, COMDAT
; Line 857
	push	ebp
	mov	ebp, esp
	push	ecx
	push	esi
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	ecx, DWORD PTR _this$[ebp]
	sub	ecx, 16					; 00000010H
	call	?GetOwner@CUnknown@@QBEPAUIUnknown@@XZ	; CUnknown::GetOwner
	mov	DWORD PTR tv72[ebp], eax
	mov	eax, DWORD PTR tv72[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	esi, esp
	mov	edx, DWORD PTR tv72[ebp]
	push	edx
	mov	eax, DWORD PTR [ecx+8]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	pop	esi
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?Release@CBaseInputPin@@UAGKXZ ENDP			; CBaseInputPin::Release
_TEXT	ENDS
PUBLIC	??1CRenderedInputPin@@UAE@XZ			; CRenderedInputPin::~CRenderedInputPin
EXTRN	??3@YAXPAX@Z:PROC				; operator delete
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??_GCRenderedInputPin@@UAEPAXI@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
___flags$ = 8						; size = 4
??_GCRenderedInputPin@@UAEPAXI@Z PROC			; CRenderedInputPin::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CRenderedInputPin@@UAE@XZ
	mov	eax, DWORD PTR ___flags$[ebp]
	and	eax, 1
	je	SHORT $LN1@scalar
	mov	ecx, DWORD PTR _this$[ebp]
	push	ecx
	call	??3@YAXPAX@Z				; operator delete
	add	esp, 4
$LN1@scalar:
	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??_GCRenderedInputPin@@UAEPAXI@Z ENDP			; CRenderedInputPin::`scalar deleting destructor'
_TEXT	ENDS
EXTRN	??1CBaseInputPin@@UAE@XZ:PROC			; CBaseInputPin::~CBaseInputPin
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??1CRenderedInputPin@@UAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1CRenderedInputPin@@UAE@XZ PROC			; CRenderedInputPin::~CRenderedInputPin, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CBaseInputPin@@UAE@XZ		; CBaseInputPin::~CBaseInputPin
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1CRenderedInputPin@@UAE@XZ ENDP			; CRenderedInputPin::~CRenderedInputPin
_TEXT	ENDS
PUBLIC	??0CRenderedInputPin@@QAE@PADPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z ; CRenderedInputPin::CRenderedInputPin
EXTRN	??0CBaseInputPin@@QAE@PADPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z:PROC ; CBaseInputPin::CBaseInputPin
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??0CRenderedInputPin@@QAE@PADPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_pObjectName$ = 8					; size = 4
_pFilter$ = 12						; size = 4
_pLock$ = 16						; size = 4
_phr$ = 20						; size = 4
_pName$ = 24						; size = 4
??0CRenderedInputPin@@QAE@PADPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z PROC ; CRenderedInputPin::CRenderedInputPin, COMDAT
; _this$ = ecx
; File c:\downloads\mediapoint\src\filters\baseclasses\amextra.cpp
; Line 40
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _pName$[ebp]
	push	eax
	mov	ecx, DWORD PTR _phr$[ebp]
	push	ecx
	mov	edx, DWORD PTR _pLock$[ebp]
	push	edx
	mov	eax, DWORD PTR _pFilter$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pObjectName$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0CBaseInputPin@@QAE@PADPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z ; CBaseInputPin::CBaseInputPin
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx], OFFSET ??_7CRenderedInputPin@@6BCUnknown@@@
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+16], OFFSET ??_7CRenderedInputPin@@6BIPin@@@
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+20], OFFSET ??_7CRenderedInputPin@@6BIQualityControl@@@
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+160], OFFSET ??_7CRenderedInputPin@@6B@
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+224], 0
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+228], 0
; Line 41
	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	20					; 00000014H
??0CRenderedInputPin@@QAE@PADPAVCBaseFilter@@PAVCCritSec@@PAJPB_W@Z ENDP ; CRenderedInputPin::CRenderedInputPin
_TEXT	ENDS
PUBLIC	?DoCompleteHandling@CRenderedInputPin@@AAEXXZ	; CRenderedInputPin::DoCompleteHandling
EXTRN	?DbgAssert@@YGXPB_W0H@Z:PROC			; DbgAssert
EXTRN	@_RTC_CheckStackVars@8:PROC
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?EndOfStream@CRenderedInputPin@@UAGJXZ
_TEXT	SEGMENT
_fs$81583 = -12						; size = 4
_hr$ = -4						; size = 4
_this$ = 8						; size = 4
?EndOfStream@CRenderedInputPin@@UAGJXZ PROC		; CRenderedInputPin::EndOfStream, COMDAT
; Line 48
	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
	push	esi
	mov	eax, -858993460				; ccccccccH
	mov	DWORD PTR [ebp-16], eax
	mov	DWORD PTR [ebp-12], eax
	mov	DWORD PTR [ebp-8], eax
	mov	DWORD PTR [ebp-4], eax
; Line 49
	mov	ecx, DWORD PTR _this$[ebp]
	sub	ecx, 16					; 00000010H
	mov	eax, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax-16]
	mov	esi, esp
	mov	eax, DWORD PTR [edx+56]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _hr$[ebp], eax
; Line 52
	cmp	DWORD PTR _hr$[ebp], 0
	jne	SHORT $LN3@EndOfStrea
	mov	ecx, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [ecx+208], 0
	jne	SHORT $LN3@EndOfStrea
; Line 53
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+208], 1
; Line 55
	mov	esi, esp
	lea	eax, DWORD PTR _fs$81583[ebp]
	push	eax
	push	0
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+28]
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	add	ecx, 16					; 00000010H
	mov	edx, DWORD PTR [edx+16]
	push	ecx
	mov	eax, DWORD PTR [edx+28]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	test	eax, eax
	jge	SHORT $LN2@EndOfStrea
	push	55					; 00000037H
	push	OFFSET $SG81586
	push	OFFSET $SG81587
	call	?DbgAssert@@YGXPB_W0H@Z			; DbgAssert
$LN2@EndOfStrea:
; Line 56
	cmp	DWORD PTR _fs$81583[ebp], 2
	jne	SHORT $LN3@EndOfStrea
; Line 57
	mov	ecx, DWORD PTR _this$[ebp]
	sub	ecx, 16					; 00000010H
	call	?DoCompleteHandling@CRenderedInputPin@@AAEXXZ ; CRenderedInputPin::DoCompleteHandling
$LN3@EndOfStrea:
; Line 60
	mov	eax, DWORD PTR _hr$[ebp]
; Line 61
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN8@EndOfStrea
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	esi
	add	esp, 16					; 00000010H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
	npad	2
$LN8@EndOfStrea:
	DD	1
	DD	$LN7@EndOfStrea
$LN7@EndOfStrea:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN6@EndOfStrea
$LN6@EndOfStrea:
	DB	102					; 00000066H
	DB	115					; 00000073H
	DB	0
?EndOfStream@CRenderedInputPin@@UAGJXZ ENDP		; CRenderedInputPin::EndOfStream
_TEXT	ENDS
PUBLIC	??1CAutoLock@@QAE@XZ				; CAutoLock::~CAutoLock
PUBLIC	??0CAutoLock@@QAE@PAVCCritSec@@@Z		; CAutoLock::CAutoLock
EXTRN	?EndFlush@CBaseInputPin@@UAGJXZ:PROC		; CBaseInputPin::EndFlush
EXTRN	___security_cookie:DWORD
EXTRN	___CxxFrameHandler3:PROC
EXTRN	@__security_check_cookie@4:PROC
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?EndFlush@CRenderedInputPin@@UAGJXZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?EndFlush@CRenderedInputPin@@UAGJXZ$0
__ehfuncinfo$?EndFlush@CRenderedInputPin@@UAGJXZ DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$?EndFlush@CRenderedInputPin@@UAGJXZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Odtp /RTCsu
xdata$x	ENDS
;	COMDAT ?EndFlush@CRenderedInputPin@@UAGJXZ
_TEXT	SEGMENT
$T82015 = -28						; size = 4
_lck$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
_this$ = 8						; size = 4
?EndFlush@CRenderedInputPin@@UAGJXZ PROC		; CRenderedInputPin::EndFlush, COMDAT
; Line 67
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?EndFlush@CRenderedInputPin@@UAGJXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 16					; 00000010H
	mov	eax, -858993460				; ccccccccH
	mov	DWORD PTR [ebp-28], eax
	mov	DWORD PTR [ebp-24], eax
	mov	DWORD PTR [ebp-20], eax
	mov	DWORD PTR [ebp-16], eax
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
; Line 68
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	push	ecx
	lea	ecx, DWORD PTR _lck$[ebp]
	call	??0CAutoLock@@QAE@PAVCCritSec@@@Z	; CAutoLock::CAutoLock
	mov	DWORD PTR __$EHRec$[ebp+8], 0
; Line 71
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+208], 0
; Line 72
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+212], 0
; Line 74
	mov	ecx, DWORD PTR _this$[ebp]
	push	ecx
	call	?EndFlush@CBaseInputPin@@UAGJXZ		; CBaseInputPin::EndFlush
	mov	DWORD PTR $T82015[ebp], eax
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR _lck$[ebp]
	call	??1CAutoLock@@QAE@XZ			; CAutoLock::~CAutoLock
	mov	eax, DWORD PTR $T82015[ebp]
; Line 75
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN7@EndFlush
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	add	esp, 28					; 0000001cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
$LN7@EndFlush:
	DD	1
	DD	$LN6@EndFlush
$LN6@EndFlush:
	DD	-20					; ffffffecH
	DD	4
	DD	$LN4@EndFlush
$LN4@EndFlush:
	DB	108					; 0000006cH
	DB	99					; 00000063H
	DB	107					; 0000006bH
	DB	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?EndFlush@CRenderedInputPin@@UAGJXZ$0:
	lea	ecx, DWORD PTR _lck$[ebp]
	jmp	??1CAutoLock@@QAE@XZ			; CAutoLock::~CAutoLock
__ehhandler$?EndFlush@CRenderedInputPin@@UAGJXZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-20]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?EndFlush@CRenderedInputPin@@UAGJXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?EndFlush@CRenderedInputPin@@UAGJXZ ENDP		; CRenderedInputPin::EndFlush
EXTRN	?Lock@CCritSec@@QAEXXZ:PROC			; CCritSec::Lock
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??0CAutoLock@@QAE@PAVCCritSec@@@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_plock$ = 8						; size = 4
??0CAutoLock@@QAE@PAVCCritSec@@@Z PROC			; CAutoLock::CAutoLock, COMDAT
; _this$ = ecx
; File c:\downloads\mediapoint\src\filters\baseclasses\wxutil.h
; Line 94
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
; Line 96
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _plock$[ebp]
	mov	DWORD PTR [eax], ecx
; Line 97
	mov	edx, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [edx]
	call	?Lock@CCritSec@@QAEXXZ			; CCritSec::Lock
; Line 98
	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??0CAutoLock@@QAE@PAVCCritSec@@@Z ENDP			; CAutoLock::CAutoLock
_TEXT	ENDS
EXTRN	?Unlock@CCritSec@@QAEXXZ:PROC			; CCritSec::Unlock
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??1CAutoLock@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1CAutoLock@@QAE@XZ PROC				; CAutoLock::~CAutoLock, COMDAT
; _this$ = ecx
; Line 100
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
; Line 101
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax]
	call	?Unlock@CCritSec@@QAEXXZ		; CCritSec::Unlock
; Line 102
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1CAutoLock@@QAE@XZ ENDP				; CAutoLock::~CAutoLock
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?Run@CRenderedInputPin@@UAEJ_J@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_tStart$ = 8						; size = 8
?Run@CRenderedInputPin@@UAEJ_J@Z PROC			; CRenderedInputPin::Run, COMDAT
; _this$ = ecx
; File c:\downloads\mediapoint\src\filters\baseclasses\amextra.cpp
; Line 81
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
; Line 83
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+228], 0
; Line 84
	mov	ecx, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [ecx+224], 0
	je	SHORT $LN1@Run
; Line 85
	mov	ecx, DWORD PTR _this$[ebp]
	call	?DoCompleteHandling@CRenderedInputPin@@AAEXXZ ; CRenderedInputPin::DoCompleteHandling
$LN1@Run:
; Line 87
	xor	eax, eax
; Line 88
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?Run@CRenderedInputPin@@UAEJ_J@Z ENDP			; CRenderedInputPin::Run
_TEXT	ENDS
EXTRN	?Active@CBasePin@@UAEJXZ:PROC			; CBasePin::Active
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?Active@CRenderedInputPin@@UAEJXZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?Active@CRenderedInputPin@@UAEJXZ PROC			; CRenderedInputPin::Active, COMDAT
; _this$ = ecx
; Line 94
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
; Line 95
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+224], 0
; Line 96
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+228], 0
; Line 97
	mov	ecx, DWORD PTR _this$[ebp]
	call	?Active@CBasePin@@UAEJXZ		; CBasePin::Active
; Line 98
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?Active@CRenderedInputPin@@UAEJXZ ENDP			; CRenderedInputPin::Active
_TEXT	ENDS
EXTRN	?NotifyEvent@CBaseFilter@@QAEJJJJ@Z:PROC	; CBaseFilter::NotifyEvent
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?DoCompleteHandling@CRenderedInputPin@@AAEXXZ
_TEXT	SEGMENT
tv88 = -12						; size = 4
tv89 = -8						; size = 4
_this$ = -4						; size = 4
?DoCompleteHandling@CRenderedInputPin@@AAEXXZ PROC	; CRenderedInputPin::DoCompleteHandling, COMDAT
; _this$ = ecx
; Line 104
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
	mov	DWORD PTR [ebp-12], -858993460		; ccccccccH
	mov	DWORD PTR [ebp-8], -858993460		; ccccccccH
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
; Line 105
	mov	eax, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [eax+224], 0
	jne	SHORT $LN2@DoComplete
	push	105					; 00000069H
	push	OFFSET $SG81607
	push	OFFSET $SG81608
	call	?DbgAssert@@YGXPB_W0H@Z			; DbgAssert
$LN2@DoComplete:
; Line 106
	mov	ecx, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [ecx+228], 0
	jne	SHORT $LN3@DoComplete
; Line 107
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+228], 1
; Line 108
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+44]
	mov	DWORD PTR tv89[ebp], ecx
	cmp	DWORD PTR tv89[ebp], 0
	je	SHORT $LN5@DoComplete
	mov	edx, DWORD PTR tv89[ebp]
	add	edx, 16					; 00000010H
	mov	DWORD PTR tv88[ebp], edx
	jmp	SHORT $LN6@DoComplete
$LN5@DoComplete:
	mov	DWORD PTR tv88[ebp], 0
$LN6@DoComplete:
	mov	eax, DWORD PTR tv88[ebp]
	push	eax
	push	0
	push	1
	mov	ecx, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [ecx+44]
	call	?NotifyEvent@CBaseFilter@@QAEJJJJ@Z	; CBaseFilter::NotifyEvent
$LN3@DoComplete:
; Line 110
	add	esp, 12					; 0000000cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?DoCompleteHandling@CRenderedInputPin@@AAEXXZ ENDP	; CRenderedInputPin::DoCompleteHandling
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?AddRef@CBaseInputPin@@WJA@AGKXZ
_TEXT	SEGMENT
?AddRef@CBaseInputPin@@WJA@AGKXZ PROC			; [thunk]:CBaseInputPin::AddRef`adjustor{144}', COMDAT
	sub	DWORD PTR [esp+4], 144			; 00000090H
	jmp	?AddRef@CBaseInputPin@@UAGKXZ		; CBaseInputPin::AddRef
?AddRef@CBaseInputPin@@WJA@AGKXZ ENDP			; [thunk]:CBaseInputPin::AddRef`adjustor{144}'
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?QueryInterface@CBaseInputPin@@WJA@AGJABU_GUID@@PAPAX@Z
_TEXT	SEGMENT
?QueryInterface@CBaseInputPin@@WJA@AGJABU_GUID@@PAPAX@Z PROC ; [thunk]:CBaseInputPin::QueryInterface`adjustor{144}', COMDAT
	sub	DWORD PTR [esp+4], 144			; 00000090H
	jmp	?QueryInterface@CBaseInputPin@@UAGJABU_GUID@@PAPAX@Z ; CBaseInputPin::QueryInterface
?QueryInterface@CBaseInputPin@@WJA@AGJABU_GUID@@PAPAX@Z ENDP ; [thunk]:CBaseInputPin::QueryInterface`adjustor{144}'
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?Release@CBaseInputPin@@W3AGKXZ
_TEXT	SEGMENT
?Release@CBaseInputPin@@W3AGKXZ PROC			; [thunk]:CBaseInputPin::Release`adjustor{4}', COMDAT
	sub	DWORD PTR [esp+4], 4
	jmp	?Release@CBaseInputPin@@UAGKXZ		; CBaseInputPin::Release
?Release@CBaseInputPin@@W3AGKXZ ENDP			; [thunk]:CBaseInputPin::Release`adjustor{4}'
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?AddRef@CBaseInputPin@@W3AGKXZ
_TEXT	SEGMENT
?AddRef@CBaseInputPin@@W3AGKXZ PROC			; [thunk]:CBaseInputPin::AddRef`adjustor{4}', COMDAT
	sub	DWORD PTR [esp+4], 4
	jmp	?AddRef@CBaseInputPin@@UAGKXZ		; CBaseInputPin::AddRef
?AddRef@CBaseInputPin@@W3AGKXZ ENDP			; [thunk]:CBaseInputPin::AddRef`adjustor{4}'
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?QueryInterface@CBaseInputPin@@W3AGJABU_GUID@@PAPAX@Z
_TEXT	SEGMENT
?QueryInterface@CBaseInputPin@@W3AGJABU_GUID@@PAPAX@Z PROC ; [thunk]:CBaseInputPin::QueryInterface`adjustor{4}', COMDAT
	sub	DWORD PTR [esp+4], 4
	jmp	?QueryInterface@CBaseInputPin@@UAGJABU_GUID@@PAPAX@Z ; CBaseInputPin::QueryInterface
?QueryInterface@CBaseInputPin@@W3AGJABU_GUID@@PAPAX@Z ENDP ; [thunk]:CBaseInputPin::QueryInterface`adjustor{4}'
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?Release@CBaseInputPin@@WJA@AGKXZ
_TEXT	SEGMENT
?Release@CBaseInputPin@@WJA@AGKXZ PROC			; [thunk]:CBaseInputPin::Release`adjustor{144}', COMDAT
	sub	DWORD PTR [esp+4], 144			; 00000090H
	jmp	?Release@CBaseInputPin@@UAGKXZ		; CBaseInputPin::Release
?Release@CBaseInputPin@@WJA@AGKXZ ENDP			; [thunk]:CBaseInputPin::Release`adjustor{144}'
_TEXT	ENDS
END
