; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Downloads\MediaPoint\src\filters\BaseClasses\dllentry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	?g_hInst@@3PAUHINSTANCE__@@A			; g_hInst
PUBLIC	?g_osInfo@@3U_OSVERSIONINFOW@@A			; g_osInfo
PUBLIC	?g_amPlatform@@3KA				; g_amPlatform
PUBLIC	_IID_IAMFilterGraphCallback
PUBLIC	?m_cLocked@CClassFactory@@0HA			; CClassFactory::m_cLocked
_BSS	SEGMENT
?g_hInst@@3PAUHINSTANCE__@@A DD 01H DUP (?)		; g_hInst
?g_osInfo@@3U_OSVERSIONINFOW@@A DB 0114H DUP (?)	; g_osInfo
?g_amPlatform@@3KA DD 01H DUP (?)			; g_amPlatform
?m_cLocked@CClassFactory@@0HA DD 01H DUP (?)		; CClassFactory::m_cLocked
_BSS	ENDS
CONST	SEGMENT
$SG82873 DB	'C', 00H, 'l', 00H, 'a', 00H, 's', 00H, 's', 00H, ' ', 00H
	DB	'F', 00H, 'a', 00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, 'y'
	DB	00H, 00H, 00H
$SG82886 DB	'.', 00H, '.', 00H, '\', 00H, 'd', 00H, 'l', 00H, 'l', 00H
	DB	'e', 00H, 'n', 00H, 't', 00H, 'r', 00H, 'y', 00H, '.', 00H, 'c'
	DB	00H, 'p', 00H, 'p', 00H, 00H, 00H
$SG82887 DB	'"', 00H, 'I', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'r', 00H, 'e', 00H, 'a', 00H, 'd'
	DB	00H, ' ', 00H, 'p', 00H, 'o', 00H, 'i', 00H, 'n', 00H, 't', 00H
	DB	'e', 00H, 'r', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG82891 DB	'.', 00H, '.', 00H, '\', 00H, 'd', 00H, 'l', 00H, 'l', 00H
	DB	'e', 00H, 'n', 00H, 't', 00H, 'r', 00H, 'y', 00H, '.', 00H, 'c'
	DB	00H, 'p', 00H, 'p', 00H, 00H, 00H
$SG82892 DB	'"', 00H, 'I', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'w', 00H, 'r', 00H, 'i', 00H, 't'
	DB	00H, 'e', 00H, ' ', 00H, 'p', 00H, 'o', 00H, 'i', 00H, 'n', 00H
	DB	't', 00H, 'e', 00H, 'r', 00H, '"', 00H, 00H, 00H
$SG82926 DB	'.', 00H, '.', 00H, '\', 00H, 'd', 00H, 'l', 00H, 'l', 00H
	DB	'e', 00H, 'n', 00H, 't', 00H, 'r', 00H, 'y', 00H, '.', 00H, 'c'
	DB	00H, 'p', 00H, 'p', 00H, 00H, 00H
$SG82927 DB	'"', 00H, 'I', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'r', 00H, 'e', 00H, 'a', 00H, 'd'
	DB	00H, ' ', 00H, 'p', 00H, 'o', 00H, 'i', 00H, 'n', 00H, 't', 00H
	DB	'e', 00H, 'r', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG82931 DB	'.', 00H, '.', 00H, '\', 00H, 'd', 00H, 'l', 00H, 'l', 00H
	DB	'e', 00H, 'n', 00H, 't', 00H, 'r', 00H, 'y', 00H, '.', 00H, 'c'
	DB	00H, 'p', 00H, 'p', 00H, 00H, 00H
$SG82932 DB	'"', 00H, 'I', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'w', 00H, 'r', 00H, 'i', 00H, 't'
	DB	00H, 'e', 00H, ' ', 00H, 'p', 00H, 'o', 00H, 'i', 00H, 'n', 00H
	DB	't', 00H, 'e', 00H, 'r', 00H, '"', 00H, 00H, 00H
$SG82950 DB	'.', 00H, '.', 00H, '\', 00H, 'd', 00H, 'l', 00H, 'l', 00H
	DB	'e', 00H, 'n', 00H, 't', 00H, 'r', 00H, 'y', 00H, '.', 00H, 'c'
	DB	00H, 'p', 00H, 'p', 00H, 00H, 00H
$SG82951 DB	'*', 00H, 'p', 00H, 'v', 00H, 00H, 00H
	ORG $+4
$SG82992 DB	'D', 00H, 'L', 00H, 'L', 00H, 'C', 00H, 'a', 00H, 'n', 00H
	DB	'U', 00H, 'n', 00H, 'l', 00H, 'o', 00H, 'a', 00H, 'd', 00H, 'N'
	DB	00H, 'o', 00H, 'w', 00H, ' ', 00H, 'c', 00H, 'a', 00H, 'l', 00H
	DB	'l', 00H, 'e', 00H, 'd', 00H, ' ', 00H, '-', 00H, ' ', 00H, 'I'
	DB	00H, 's', 00H, 'L', 00H, 'o', 00H, 'c', 00H, 'k', 00H, 'e', 00H
	DB	'd', 00H, ' ', 00H, '=', 00H, ' ', 00H, '%', 00H, 'd', 00H, ','
	DB	00H, ' ', 00H, 'A', 00H, 'c', 00H, 't', 00H, 'i', 00H, 'v', 00H
	DB	'e', 00H, ' ', 00H, 'o', 00H, 'b', 00H, 'j', 00H, 'e', 00H, 'c'
	DB	00H, 't', 00H, 's', 00H, ' ', 00H, '=', 00H, ' ', 00H, '%', 00H
	DB	'd', 00H, 00H, 00H
$SG83015 DB	'F', 00H, 'a', 00H, 'i', 00H, 'l', 00H, 'e', 00H, 'd', 00H
	DB	' ', 00H, 't', 00H, 'o', 00H, ' ', 00H, 'g', 00H, 'e', 00H, 't'
	DB	00H, ' ', 00H, 't', 00H, 'h', 00H, 'e', 00H, ' ', 00H, 'O', 00H
	DB	'S', 00H, ' ', 00H, 'p', 00H, 'l', 00H, 'a', 00H, 't', 00H, 'f'
	DB	00H, 'o', 00H, 'r', 00H, 'm', 00H, ',', 00H, ' ', 00H, 'a', 00H
	DB	's', 00H, 's', 00H, 'u', 00H, 'm', 00H, 'i', 00H, 'n', 00H, 'g'
	DB	00H, ' ', 00H, 'W', 00H, 'i', 00H, 'n', 00H, '9', 00H, '5', 00H
	DB	00H, 00H
	ORG $+4
$SG83025 DB	'E', 00H, 'x', 00H, 'e', 00H, 'c', 00H, 'u', 00H, 't', 00H
	DB	'a', 00H, 'b', 00H, 'l', 00H, 'e', 00H, ':', 00H, ' ', 00H, '%'
	DB	00H, 's', 00H, ' ', 00H, ' ', 00H, 'P', 00H, 'i', 00H, 'd', 00H
	DB	' ', 00H, '%', 00H, 'x', 00H, ' ', 00H, ' ', 00H, 'T', 00H, 'i'
	DB	00H, 'd', 00H, ' ', 00H, '%', 00H, 'x', 00H, '.', 00H, ' ', 00H
	DB	00H, 00H
	ORG $+6
$SG83026 DB	'M', 00H, 'o', 00H, 'd', 00H, 'u', 00H, 'l', 00H, 'e', 00H
	DB	' ', 00H, '%', 00H, 's', 00H, ',', 00H, ' ', 00H, '%', 00H, 'd'
	DB	00H, ' ', 00H, 'o', 00H, 'b', 00H, 'j', 00H, 'e', 00H, 'c', 00H
	DB	't', 00H, 's', 00H, ' ', 00H, 'l', 00H, 'e', 00H, 'f', 00H, 't'
	DB	00H, ' ', 00H, 'a', 00H, 'c', 00H, 't', 00H, 'i', 00H, 'v', 00H
	DB	'e', 00H, '!', 00H, 00H, 00H
	ORG $+2
$SG83027 DB	'.', 00H, '.', 00H, '\', 00H, 'd', 00H, 'l', 00H, 'l', 00H
	DB	'e', 00H, 'n', 00H, 't', 00H, 'r', 00H, 'y', 00H, '.', 00H, 'c'
	DB	00H, 'p', 00H, 'p', 00H, 00H, 00H
CONST	ENDS
;	COMDAT _IID_IAMFilterGraphCallback
CONST	SEGMENT
_IID_IAMFilterGraphCallback DD 056a868fdH
	DW	0ad4H
	DW	011ceH
	DB	0b0H
	DB	0a3H
	DB	00H
	DB	020H
	DB	0afH
	DB	0bH
	DB	0a7H
	DB	070H
CONST	ENDS
PUBLIC	??_7CClassFactory@@6B@				; CClassFactory::`vftable'
PUBLIC	??0IClassFactory@@QAE@XZ			; IClassFactory::IClassFactory
PUBLIC	??0CClassFactory@@QAE@PBVCFactoryTemplate@@@Z	; CClassFactory::CClassFactory
PUBLIC	??_R4CClassFactory@@6B@				; CClassFactory::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCClassFactory@@@8			; CClassFactory `RTTI Type Descriptor'
PUBLIC	??_R3CClassFactory@@8				; CClassFactory::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CClassFactory@@8				; CClassFactory::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CClassFactory@@8			; CClassFactory::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@IClassFactory@@8			; IClassFactory::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AUIClassFactory@@@8			; IClassFactory `RTTI Type Descriptor'
PUBLIC	??_R3IClassFactory@@8				; IClassFactory::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IClassFactory@@8				; IClassFactory::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@IUnknown@@8			; IUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AUIUnknown@@@8				; IUnknown `RTTI Type Descriptor'
PUBLIC	??_R3IUnknown@@8				; IUnknown::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IUnknown@@8				; IUnknown::`RTTI Base Class Array'
PUBLIC	??_R13?0A@EA@CBaseObject@@8			; CBaseObject::`RTTI Base Class Descriptor at (4,-1,0,64)'
PUBLIC	??_R0?AVCBaseObject@@@8				; CBaseObject `RTTI Type Descriptor'
PUBLIC	??_R3CBaseObject@@8				; CBaseObject::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CBaseObject@@8				; CBaseObject::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CBaseObject@@8			; CBaseObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	?QueryInterface@CClassFactory@@UAGJABU_GUID@@PAPAX@Z ; CClassFactory::QueryInterface
PUBLIC	?AddRef@CClassFactory@@UAGKXZ			; CClassFactory::AddRef
PUBLIC	?Release@CClassFactory@@UAGKXZ			; CClassFactory::Release
PUBLIC	?CreateInstance@CClassFactory@@UAGJPAUIUnknown@@ABU_GUID@@PAPAX@Z ; CClassFactory::CreateInstance
PUBLIC	?LockServer@CClassFactory@@UAGJH@Z		; CClassFactory::LockServer
EXTRN	??0CBaseObject@@QAE@PB_W@Z:PROC			; CBaseObject::CBaseObject
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
;	COMDAT ??_R1A@?0A@EA@CBaseObject@@8
; File c:\downloads\mediapoint\src\filters\baseclasses\dllentry.cpp
rdata$r	SEGMENT
??_R1A@?0A@EA@CBaseObject@@8 DD FLAT:??_R0?AVCBaseObject@@@8 ; CBaseObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CBaseObject@@8
rdata$r	ENDS
;	COMDAT ??_R2CBaseObject@@8
rdata$r	SEGMENT
??_R2CBaseObject@@8 DD FLAT:??_R1A@?0A@EA@CBaseObject@@8 ; CBaseObject::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3CBaseObject@@8
rdata$r	SEGMENT
??_R3CBaseObject@@8 DD 00H				; CBaseObject::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2CBaseObject@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCBaseObject@@@8
_DATA	SEGMENT
??_R0?AVCBaseObject@@@8 DD FLAT:??_7type_info@@6B@	; CBaseObject `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCBaseObject@@', 00H
_DATA	ENDS
;	COMDAT ??_R13?0A@EA@CBaseObject@@8
rdata$r	SEGMENT
??_R13?0A@EA@CBaseObject@@8 DD FLAT:??_R0?AVCBaseObject@@@8 ; CBaseObject::`RTTI Base Class Descriptor at (4,-1,0,64)'
	DD	00H
	DD	04H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CBaseObject@@8
rdata$r	ENDS
;	COMDAT ??_R2IUnknown@@8
rdata$r	SEGMENT
??_R2IUnknown@@8 DD FLAT:??_R1A@?0A@EA@IUnknown@@8	; IUnknown::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3IUnknown@@8
rdata$r	SEGMENT
??_R3IUnknown@@8 DD 00H					; IUnknown::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIUnknown@@@8
_DATA	SEGMENT
??_R0?AUIUnknown@@@8 DD FLAT:??_7type_info@@6B@		; IUnknown `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIUnknown@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@IUnknown@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IUnknown@@8 DD FLAT:??_R0?AUIUnknown@@@8	; IUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R2IClassFactory@@8
rdata$r	SEGMENT
??_R2IClassFactory@@8 DD FLAT:??_R1A@?0A@EA@IClassFactory@@8 ; IClassFactory::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R3IClassFactory@@8
rdata$r	SEGMENT
??_R3IClassFactory@@8 DD 00H				; IClassFactory::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2IClassFactory@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIClassFactory@@@8
_DATA	SEGMENT
??_R0?AUIClassFactory@@@8 DD FLAT:??_7type_info@@6B@	; IClassFactory `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIClassFactory@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@IClassFactory@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IClassFactory@@8 DD FLAT:??_R0?AUIClassFactory@@@8 ; IClassFactory::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IClassFactory@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CClassFactory@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CClassFactory@@8 DD FLAT:??_R0?AVCClassFactory@@@8 ; CClassFactory::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	03H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CClassFactory@@8
rdata$r	ENDS
;	COMDAT ??_R2CClassFactory@@8
rdata$r	SEGMENT
??_R2CClassFactory@@8 DD FLAT:??_R1A@?0A@EA@CClassFactory@@8 ; CClassFactory::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IClassFactory@@8
	DD	FLAT:??_R1A@?0A@EA@IUnknown@@8
	DD	FLAT:??_R13?0A@EA@CBaseObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CClassFactory@@8
rdata$r	SEGMENT
??_R3CClassFactory@@8 DD 00H				; CClassFactory::`RTTI Class Hierarchy Descriptor'
	DD	01H
	DD	04H
	DD	FLAT:??_R2CClassFactory@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCClassFactory@@@8
_DATA	SEGMENT
??_R0?AVCClassFactory@@@8 DD FLAT:??_7type_info@@6B@	; CClassFactory `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCClassFactory@@', 00H
_DATA	ENDS
;	COMDAT ??_R4CClassFactory@@6B@
rdata$r	SEGMENT
??_R4CClassFactory@@6B@ DD 00H				; CClassFactory::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCClassFactory@@@8
	DD	FLAT:??_R3CClassFactory@@8
rdata$r	ENDS
;	COMDAT ??_7CClassFactory@@6B@
CONST	SEGMENT
??_7CClassFactory@@6B@ DD FLAT:??_R4CClassFactory@@6B@	; CClassFactory::`vftable'
	DD	FLAT:?QueryInterface@CClassFactory@@UAGJABU_GUID@@PAPAX@Z
	DD	FLAT:?AddRef@CClassFactory@@UAGKXZ
	DD	FLAT:?Release@CClassFactory@@UAGKXZ
	DD	FLAT:?CreateInstance@CClassFactory@@UAGJPAUIUnknown@@ABU_GUID@@PAPAX@Z
	DD	FLAT:?LockServer@CClassFactory@@UAGJH@Z
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu
rtc$IMZ	ENDS
;	COMDAT ??0CClassFactory@@QAE@PBVCFactoryTemplate@@@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_pTemplate$ = 8						; size = 4
??0CClassFactory@@QAE@PBVCFactoryTemplate@@@Z PROC	; CClassFactory::CClassFactory, COMDAT
; _this$ = ecx
; Line 70
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0IClassFactory@@QAE@XZ
	push	OFFSET $SG82873
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??0CBaseObject@@QAE@PB_W@Z		; CBaseObject::CBaseObject
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CClassFactory@@6B@
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _pTemplate$[ebp]
	mov	DWORD PTR [ecx+8], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+12], 0
; Line 71
	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??0CClassFactory@@QAE@PBVCFactoryTemplate@@@Z ENDP	; CClassFactory::CClassFactory
_TEXT	ENDS
PUBLIC	??0IUnknown@@QAE@XZ				; IUnknown::IUnknown
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??0IClassFactory@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0IClassFactory@@QAE@XZ PROC				; IClassFactory::IClassFactory, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0IUnknown@@QAE@XZ
	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??0IClassFactory@@QAE@XZ ENDP				; IClassFactory::IClassFactory
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ??0IUnknown@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0IUnknown@@QAE@XZ PROC				; IUnknown::IUnknown, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0IUnknown@@QAE@XZ ENDP				; IUnknown::IUnknown
_TEXT	ENDS
PUBLIC	_==@8
EXTRN	_IID_IClassFactory:BYTE
EXTRN	_IID_IUnknown:BYTE
EXTRN	__imp__IsBadWritePtr@8:PROC
EXTRN	?DbgBreakPoint@@YGXPB_W0H@Z:PROC		; DbgBreakPoint
EXTRN	__imp__IsBadReadPtr@8:PROC
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?QueryInterface@CClassFactory@@UAGJABU_GUID@@PAPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_riid$ = 12						; size = 4
_ppv$ = 16						; size = 4
?QueryInterface@CClassFactory@@UAGJABU_GUID@@PAPAX@Z PROC ; CClassFactory::QueryInterface, COMDAT
; Line 76
	push	ebp
	mov	ebp, esp
	push	esi
; Line 77
	cmp	DWORD PTR _ppv$[ebp], 0
	jne	SHORT $LN5@QueryInter
	mov	eax, -2147467261			; 80004003H
	jmp	$LN6@QueryInter
$LN5@QueryInter:
; Line 78
	mov	esi, esp
	push	4
	mov	eax, DWORD PTR _ppv$[ebp]
	push	eax
	call	DWORD PTR __imp__IsBadReadPtr@8
	cmp	esi, esp
	call	__RTC_CheckEsp
	cmp	eax, 1
	jne	SHORT $LN4@QueryInter
	push	78					; 0000004eH
	push	OFFSET $SG82886
	push	OFFSET $SG82887
	call	?DbgBreakPoint@@YGXPB_W0H@Z		; DbgBreakPoint
$LN4@QueryInter:
	mov	esi, esp
	push	4
	mov	ecx, DWORD PTR _ppv$[ebp]
	push	ecx
	call	DWORD PTR __imp__IsBadWritePtr@8
	cmp	esi, esp
	call	__RTC_CheckEsp
	cmp	eax, 1
	jne	SHORT $LN3@QueryInter
	push	78					; 0000004eH
	push	OFFSET $SG82891
	push	OFFSET $SG82892
	call	?DbgBreakPoint@@YGXPB_W0H@Z		; DbgBreakPoint
$LN3@QueryInter:
; Line 79
	mov	edx, DWORD PTR _ppv$[ebp]
	mov	DWORD PTR [edx], 0
; Line 82
	push	OFFSET _IID_IUnknown
	mov	eax, DWORD PTR _riid$[ebp]
	push	eax
	call	_==@8
	test	eax, eax
	jne	SHORT $LN1@QueryInter
	push	OFFSET _IID_IClassFactory
	mov	ecx, DWORD PTR _riid$[ebp]
	push	ecx
	call	_==@8
	test	eax, eax
	je	SHORT $LN2@QueryInter
$LN1@QueryInter:
; Line 83
	mov	edx, DWORD PTR _ppv$[ebp]
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx], eax
; Line 85
	mov	ecx, DWORD PTR _ppv$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	eax, DWORD PTR _ppv$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [edx]
	mov	esi, esp
	push	ecx
	mov	eax, DWORD PTR [edx+4]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 86
	xor	eax, eax
	jmp	SHORT $LN6@QueryInter
$LN2@QueryInter:
; Line 89
	mov	eax, -2147467262			; 80004002H
$LN6@QueryInter:
; Line 90
	pop	esi
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	12					; 0000000cH
?QueryInterface@CClassFactory@@UAGJABU_GUID@@PAPAX@Z ENDP ; CClassFactory::QueryInterface
_TEXT	ENDS
PUBLIC	_IsEqualGUID@8
; Function compile flags: /Odtp /RTCsu
;	COMDAT _==@8
_TEXT	SEGMENT
_guidOne$ = 8						; size = 4
_guidOther$ = 12					; size = 4
_==@8	PROC						; COMDAT
; File c:\program files (x86)\microsoft sdks\windows\v7.0a\include\guiddef.h
; Line 193
	push	ebp
	mov	ebp, esp
; Line 194
	mov	eax, DWORD PTR _guidOther$[ebp]
	push	eax
	mov	ecx, DWORD PTR _guidOne$[ebp]
	push	ecx
	call	_IsEqualGUID@8
; Line 195
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	8
_==@8	ENDP
_TEXT	ENDS
EXTRN	_memcmp:PROC
; Function compile flags: /Odtp /RTCsu
;	COMDAT _IsEqualGUID@8
_TEXT	SEGMENT
_rguid1$ = 8						; size = 4
_rguid2$ = 12						; size = 4
_IsEqualGUID@8 PROC					; COMDAT
; Line 160
	push	ebp
	mov	ebp, esp
; Line 161
	push	16					; 00000010H
	mov	eax, DWORD PTR _rguid2$[ebp]
	push	eax
	mov	ecx, DWORD PTR _rguid1$[ebp]
	push	ecx
	call	_memcmp
	add	esp, 12					; 0000000cH
	neg	eax
	sbb	eax, eax
	add	eax, 1
; Line 162
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	8
_IsEqualGUID@8 ENDP
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?AddRef@CClassFactory@@UAGKXZ
_TEXT	SEGMENT
tv66 = -4						; size = 4
_this$ = 8						; size = 4
?AddRef@CClassFactory@@UAGKXZ PROC			; CClassFactory::AddRef, COMDAT
; File c:\downloads\mediapoint\src\filters\baseclasses\dllentry.cpp
; Line 95
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
; Line 96
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	add	ecx, 1
	mov	DWORD PTR tv66[ebp], ecx
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR tv66[ebp]
	mov	DWORD PTR [edx+12], eax
	mov	eax, DWORD PTR tv66[ebp]
; Line 97
	mov	esp, ebp
	pop	ebp
	ret	4
?AddRef@CClassFactory@@UAGKXZ ENDP			; CClassFactory::AddRef
_TEXT	ENDS
PUBLIC	??_GCClassFactory@@QAEPAXI@Z			; CClassFactory::`scalar deleting destructor'
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?Release@CClassFactory@@UAGKXZ
_TEXT	SEGMENT
tv72 = -16						; size = 4
tv66 = -12						; size = 4
$T83372 = -8						; size = 4
$T83371 = -4						; size = 4
_this$ = 8						; size = 4
?Release@CClassFactory@@UAGKXZ PROC			; CClassFactory::Release, COMDAT
; Line 101
	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
	mov	eax, -858993460				; ccccccccH
	mov	DWORD PTR [ebp-16], eax
	mov	DWORD PTR [ebp-12], eax
	mov	DWORD PTR [ebp-8], eax
	mov	DWORD PTR [ebp-4], eax
; Line 102
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	sub	ecx, 1
	mov	DWORD PTR tv66[ebp], ecx
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR tv66[ebp]
	mov	DWORD PTR [edx+12], eax
	cmp	DWORD PTR tv66[ebp], 0
	jne	SHORT $LN2@Release
; Line 103
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR $T83372[ebp], ecx
	mov	edx, DWORD PTR $T83372[ebp]
	mov	DWORD PTR $T83371[ebp], edx
	cmp	DWORD PTR $T83371[ebp], 0
	je	SHORT $LN5@Release
	push	1
	mov	ecx, DWORD PTR $T83371[ebp]
	call	??_GCClassFactory@@QAEPAXI@Z
	mov	DWORD PTR tv72[ebp], eax
	jmp	SHORT $LN6@Release
$LN5@Release:
	mov	DWORD PTR tv72[ebp], 0
$LN6@Release:
; Line 104
	xor	eax, eax
	jmp	SHORT $LN3@Release
; Line 105
	jmp	SHORT $LN3@Release
$LN2@Release:
; Line 106
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+12]
$LN3@Release:
; Line 108
	add	esp, 16					; 00000010H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?Release@CClassFactory@@UAGKXZ ENDP			; CClassFactory::Release
_TEXT	ENDS
PUBLIC	??1CClassFactory@@QAE@XZ			; CClassFactory::~CClassFactory
EXTRN	??3@YAXPAX@Z:PROC				; operator delete
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??_GCClassFactory@@QAEPAXI@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
___flags$ = 8						; size = 4
??_GCClassFactory@@QAEPAXI@Z PROC			; CClassFactory::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CClassFactory@@QAE@XZ
	mov	eax, DWORD PTR ___flags$[ebp]
	and	eax, 1
	je	SHORT $LN1@scalar
	mov	ecx, DWORD PTR _this$[ebp]
	push	ecx
	call	??3@YAXPAX@Z				; operator delete
	add	esp, 4
$LN1@scalar:
	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??_GCClassFactory@@QAEPAXI@Z ENDP			; CClassFactory::`scalar deleting destructor'
_TEXT	ENDS
EXTRN	??1CBaseObject@@QAE@XZ:PROC			; CBaseObject::~CBaseObject
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??1CClassFactory@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1CClassFactory@@QAE@XZ PROC				; CClassFactory::~CClassFactory, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??1CBaseObject@@QAE@XZ			; CBaseObject::~CBaseObject
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1CClassFactory@@QAE@XZ ENDP				; CClassFactory::~CClassFactory
_TEXT	ENDS
PUBLIC	?CreateInstance@CFactoryTemplate@@QBEPAVCUnknown@@PAUIUnknown@@PAJ@Z ; CFactoryTemplate::CreateInstance
EXTRN	?DbgAssert@@YGXPB_W0H@Z:PROC			; DbgAssert
EXTRN	@_RTC_CheckStackVars@8:PROC
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?CreateInstance@CClassFactory@@UAGJPAUIUnknown@@ABU_GUID@@PAPAX@Z
_TEXT	SEGMENT
tv130 = -28						; size = 4
$T83383 = -24						; size = 4
$T83382 = -20						; size = 4
_pObj$ = -16						; size = 4
_hr$ = -8						; size = 4
_this$ = 8						; size = 4
_pUnkOuter$ = 12					; size = 4
_riid$ = 16						; size = 4
_pv$ = 20						; size = 4
?CreateInstance@CClassFactory@@UAGJPAUIUnknown@@ABU_GUID@@PAPAX@Z PROC ; CClassFactory::CreateInstance, COMDAT
; Line 115
	push	ebp
	mov	ebp, esp
	sub	esp, 28					; 0000001cH
	push	esi
	mov	eax, -858993460				; ccccccccH
	mov	DWORD PTR [ebp-28], eax
	mov	DWORD PTR [ebp-24], eax
	mov	DWORD PTR [ebp-20], eax
	mov	DWORD PTR [ebp-16], eax
	mov	DWORD PTR [ebp-12], eax
	mov	DWORD PTR [ebp-8], eax
	mov	DWORD PTR [ebp-4], eax
; Line 116
	cmp	DWORD PTR _pv$[ebp], 0
	jne	SHORT $LN10@CreateInst
	mov	eax, -2147467261			; 80004003H
	jmp	$LN11@CreateInst
$LN10@CreateInst:
; Line 117
	mov	esi, esp
	push	4
	mov	eax, DWORD PTR _pv$[ebp]
	push	eax
	call	DWORD PTR __imp__IsBadReadPtr@8
	cmp	esi, esp
	call	__RTC_CheckEsp
	cmp	eax, 1
	jne	SHORT $LN9@CreateInst
	push	117					; 00000075H
	push	OFFSET $SG82926
	push	OFFSET $SG82927
	call	?DbgBreakPoint@@YGXPB_W0H@Z		; DbgBreakPoint
$LN9@CreateInst:
	mov	esi, esp
	push	4
	mov	ecx, DWORD PTR _pv$[ebp]
	push	ecx
	call	DWORD PTR __imp__IsBadWritePtr@8
	cmp	esi, esp
	call	__RTC_CheckEsp
	cmp	eax, 1
	jne	SHORT $LN8@CreateInst
	push	117					; 00000075H
	push	OFFSET $SG82931
	push	OFFSET $SG82932
	call	?DbgBreakPoint@@YGXPB_W0H@Z		; DbgBreakPoint
$LN8@CreateInst:
; Line 121
	cmp	DWORD PTR _pUnkOuter$[ebp], 0
	je	SHORT $LN7@CreateInst
; Line 122
	push	OFFSET _IID_IUnknown
	mov	edx, DWORD PTR _riid$[ebp]
	push	edx
	call	_IsEqualGUID@8
	test	eax, eax
	jne	SHORT $LN7@CreateInst
; Line 123
	mov	eax, -2147467262			; 80004002H
	jmp	$LN11@CreateInst
$LN7@CreateInst:
; Line 129
	mov	DWORD PTR _hr$[ebp], 0
; Line 130
	lea	eax, DWORD PTR _hr$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pUnkOuter$[ebp]
	push	ecx
	mov	edx, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [edx+8]
	call	?CreateInstance@CFactoryTemplate@@QBEPAVCUnknown@@PAUIUnknown@@PAJ@Z ; CFactoryTemplate::CreateInstance
	mov	DWORD PTR _pObj$[ebp], eax
; Line 132
	cmp	DWORD PTR _pObj$[ebp], 0
	jne	SHORT $LN5@CreateInst
; Line 133
	cmp	DWORD PTR _hr$[ebp], 0
	jl	SHORT $LN4@CreateInst
; Line 134
	mov	DWORD PTR _hr$[ebp], -2147024882	; 8007000eH
$LN4@CreateInst:
; Line 136
	mov	eax, DWORD PTR _hr$[ebp]
	jmp	$LN11@CreateInst
$LN5@CreateInst:
; Line 141
	cmp	DWORD PTR _hr$[ebp], 0
	jge	SHORT $LN3@CreateInst
; Line 142
	mov	eax, DWORD PTR _pObj$[ebp]
	mov	DWORD PTR $T83383[ebp], eax
	mov	ecx, DWORD PTR $T83383[ebp]
	mov	DWORD PTR $T83382[ebp], ecx
	cmp	DWORD PTR $T83382[ebp], 0
	je	SHORT $LN13@CreateInst
	mov	esi, esp
	push	1
	mov	edx, DWORD PTR $T83382[ebp]
	mov	eax, DWORD PTR [edx]
	mov	ecx, DWORD PTR $T83382[ebp]
	mov	edx, DWORD PTR [eax+12]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR tv130[ebp], eax
	jmp	SHORT $LN14@CreateInst
$LN13@CreateInst:
	mov	DWORD PTR tv130[ebp], 0
$LN14@CreateInst:
; Line 143
	mov	eax, DWORD PTR _hr$[ebp]
	jmp	SHORT $LN11@CreateInst
$LN3@CreateInst:
; Line 152
	mov	eax, DWORD PTR _pObj$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	esi, esp
	mov	edx, DWORD PTR _pObj$[ebp]
	push	edx
	mov	eax, DWORD PTR [ecx+4]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 153
	mov	esi, esp
	mov	ecx, DWORD PTR _pv$[ebp]
	push	ecx
	mov	edx, DWORD PTR _riid$[ebp]
	push	edx
	mov	eax, DWORD PTR _pObj$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR _pObj$[ebp]
	push	edx
	mov	eax, DWORD PTR [ecx]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _hr$[ebp], eax
; Line 154
	mov	ecx, DWORD PTR _pObj$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	esi, esp
	mov	eax, DWORD PTR _pObj$[ebp]
	push	eax
	mov	ecx, DWORD PTR [edx+8]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 161
	cmp	DWORD PTR _hr$[ebp], 0
	jl	SHORT $LN2@CreateInst
; Line 162
	mov	edx, DWORD PTR _pv$[ebp]
	cmp	DWORD PTR [edx], 0
	jne	SHORT $LN2@CreateInst
	push	162					; 000000a2H
	push	OFFSET $SG82950
	push	OFFSET $SG82951
	call	?DbgAssert@@YGXPB_W0H@Z			; DbgAssert
$LN2@CreateInst:
; Line 165
	mov	eax, DWORD PTR _hr$[ebp]
$LN11@CreateInst:
; Line 166
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN17@CreateInst
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	esi
	add	esp, 28					; 0000001cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
$LN17@CreateInst:
	DD	1
	DD	$LN16@CreateInst
$LN16@CreateInst:
	DD	-8					; fffffff8H
	DD	4
	DD	$LN15@CreateInst
$LN15@CreateInst:
	DB	104					; 00000068H
	DB	114					; 00000072H
	DB	0
?CreateInstance@CClassFactory@@UAGJPAUIUnknown@@ABU_GUID@@PAPAX@Z ENDP ; CClassFactory::CreateInstance
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?CreateInstance@CFactoryTemplate@@QBEPAVCUnknown@@PAUIUnknown@@PAJ@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_pUnk$ = 8						; size = 4
_phr$ = 12						; size = 4
?CreateInstance@CFactoryTemplate@@QBEPAVCUnknown@@PAUIUnknown@@PAJ@Z PROC ; CFactoryTemplate::CreateInstance, COMDAT
; _this$ = ecx
; File c:\downloads\mediapoint\src\filters\baseclasses\combase.h
; Line 288
	push	ebp
	mov	ebp, esp
	push	ecx
	push	esi
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
; Line 289
	cmp	DWORD PTR _phr$[ebp], 0
	jne	SHORT $LN1@CreateInst@2
	xor	eax, eax
	jmp	SHORT $LN2@CreateInst@2
$LN1@CreateInst@2:
; Line 290
	mov	esi, esp
	mov	eax, DWORD PTR _phr$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pUnk$[ebp]
	push	ecx
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+8]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN2@CreateInst@2:
; Line 291
	pop	esi
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?CreateInstance@CFactoryTemplate@@QBEPAVCUnknown@@PAUIUnknown@@PAJ@Z ENDP ; CFactoryTemplate::CreateInstance
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?LockServer@CClassFactory@@UAGJH@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_fLock$ = 12						; size = 4
?LockServer@CClassFactory@@UAGJH@Z PROC			; CClassFactory::LockServer, COMDAT
; File c:\downloads\mediapoint\src\filters\baseclasses\dllentry.cpp
; Line 170
	push	ebp
	mov	ebp, esp
; Line 171
	cmp	DWORD PTR _fLock$[ebp], 0
	je	SHORT $LN2@LockServer
; Line 172
	mov	eax, DWORD PTR ?m_cLocked@CClassFactory@@0HA ; CClassFactory::m_cLocked
	add	eax, 1
	mov	DWORD PTR ?m_cLocked@CClassFactory@@0HA, eax ; CClassFactory::m_cLocked
; Line 173
	jmp	SHORT $LN1@LockServer
$LN2@LockServer:
; Line 174
	mov	ecx, DWORD PTR ?m_cLocked@CClassFactory@@0HA ; CClassFactory::m_cLocked
	sub	ecx, 1
	mov	DWORD PTR ?m_cLocked@CClassFactory@@0HA, ecx ; CClassFactory::m_cLocked
$LN1@LockServer:
; Line 176
	xor	eax, eax
; Line 177
	pop	ebp
	ret	8
?LockServer@CClassFactory@@UAGJH@Z ENDP			; CClassFactory::LockServer
_TEXT	ENDS
PUBLIC	?IsClassID@CFactoryTemplate@@QBEHABU_GUID@@@Z	; CFactoryTemplate::IsClassID
PUBLIC	_DllGetClassObject@12
EXTRN	??2@YAPAXI@Z:PROC				; operator new
EXTRN	?g_Templates@@3PAVCFactoryTemplate@@A:BYTE	; g_Templates
EXTRN	?g_cTemplates@@3HA:DWORD			; g_cTemplates
; Function compile flags: /Odtp /RTCsu
;	COMDAT _DllGetClassObject@12
_TEXT	SEGMENT
tv91 = -20						; size = 4
$T83397 = -16						; size = 4
$T83396 = -12						; size = 4
_pT$82969 = -8						; size = 4
_i$82965 = -4						; size = 4
_rClsID$ = 8						; size = 4
_riid$ = 12						; size = 4
_pv$ = 16						; size = 4
_DllGetClassObject@12 PROC				; COMDAT
; Line 188
	push	ebp
	mov	ebp, esp
	sub	esp, 20					; 00000014H
	push	esi
	mov	eax, -858993460				; ccccccccH
	mov	DWORD PTR [ebp-20], eax
	mov	DWORD PTR [ebp-16], eax
	mov	DWORD PTR [ebp-12], eax
	mov	DWORD PTR [ebp-8], eax
	mov	DWORD PTR [ebp-4], eax
; Line 189
	push	OFFSET _IID_IUnknown
	mov	eax, DWORD PTR _riid$[ebp]
	push	eax
	call	_==@8
	test	eax, eax
	jne	SHORT $LN6@DllGetClas
	push	OFFSET _IID_IClassFactory
	mov	ecx, DWORD PTR _riid$[ebp]
	push	ecx
	call	_==@8
	test	eax, eax
	jne	SHORT $LN6@DllGetClas
; Line 190
	mov	eax, -2147467262			; 80004002H
	jmp	$LN7@DllGetClas
$LN6@DllGetClas:
; Line 195
	mov	DWORD PTR _i$82965[ebp], 0
	jmp	SHORT $LN5@DllGetClas
$LN4@DllGetClas:
	mov	edx, DWORD PTR _i$82965[ebp]
	add	edx, 1
	mov	DWORD PTR _i$82965[ebp], edx
$LN5@DllGetClas:
	mov	eax, DWORD PTR _i$82965[ebp]
	cmp	eax, DWORD PTR ?g_cTemplates@@3HA	; g_cTemplates
	jge	$LN3@DllGetClas
; Line 196
	mov	ecx, DWORD PTR _i$82965[ebp]
	imul	ecx, 20					; 00000014H
	add	ecx, OFFSET ?g_Templates@@3PAVCFactoryTemplate@@A ; g_Templates
	mov	DWORD PTR _pT$82969[ebp], ecx
; Line 197
	mov	edx, DWORD PTR _rClsID$[ebp]
	push	edx
	mov	ecx, DWORD PTR _pT$82969[ebp]
	call	?IsClassID@CFactoryTemplate@@QBEHABU_GUID@@@Z ; CFactoryTemplate::IsClassID
	test	eax, eax
	je	SHORT $LN2@DllGetClas
; Line 202
	push	16					; 00000010H
	call	??2@YAPAXI@Z				; operator new
	add	esp, 4
	mov	DWORD PTR $T83397[ebp], eax
	cmp	DWORD PTR $T83397[ebp], 0
	je	SHORT $LN9@DllGetClas
	mov	eax, DWORD PTR _pT$82969[ebp]
	push	eax
	mov	ecx, DWORD PTR $T83397[ebp]
	call	??0CClassFactory@@QAE@PBVCFactoryTemplate@@@Z ; CClassFactory::CClassFactory
	mov	DWORD PTR tv91[ebp], eax
	jmp	SHORT $LN10@DllGetClas
$LN9@DllGetClas:
	mov	DWORD PTR tv91[ebp], 0
$LN10@DllGetClas:
	mov	ecx, DWORD PTR tv91[ebp]
	mov	DWORD PTR $T83396[ebp], ecx
	mov	edx, DWORD PTR _pv$[ebp]
	mov	eax, DWORD PTR $T83396[ebp]
	mov	DWORD PTR [edx], eax
; Line 203
	mov	ecx, DWORD PTR _pv$[ebp]
	cmp	DWORD PTR [ecx], 0
	jne	SHORT $LN1@DllGetClas
; Line 204
	mov	eax, -2147024882			; 8007000eH
	jmp	SHORT $LN7@DllGetClas
$LN1@DllGetClas:
; Line 206
	mov	edx, DWORD PTR _pv$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	ecx, DWORD PTR _pv$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	eax, DWORD PTR [eax]
	mov	esi, esp
	push	edx
	mov	ecx, DWORD PTR [eax+4]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 207
	xor	eax, eax
	jmp	SHORT $LN7@DllGetClas
$LN2@DllGetClas:
; Line 209
	jmp	$LN4@DllGetClas
$LN3@DllGetClas:
; Line 210
	mov	eax, -2147221231			; 80040111H
$LN7@DllGetClas:
; Line 211
	pop	esi
	add	esp, 20					; 00000014H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
_DllGetClassObject@12 ENDP
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?IsClassID@CFactoryTemplate@@QBEHABU_GUID@@@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_rclsid$ = 8						; size = 4
?IsClassID@CFactoryTemplate@@QBEHABU_GUID@@@Z PROC	; CFactoryTemplate::IsClassID, COMDAT
; _this$ = ecx
; File c:\downloads\mediapoint\src\filters\baseclasses\combase.h
; Line 284
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
; Line 285
	mov	eax, DWORD PTR _rclsid$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	push	edx
	call	_IsEqualGUID@8
; Line 286
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?IsClassID@CFactoryTemplate@@QBEHABU_GUID@@@Z ENDP	; CFactoryTemplate::IsClassID
_TEXT	ENDS
PUBLIC	?DllInitClasses@@YGXH@Z				; DllInitClasses
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?DllInitClasses@@YGXH@Z
_TEXT	SEGMENT
_pT$82988 = -8						; size = 4
_i$ = -4						; size = 4
_bLoading$ = 8						; size = 4
?DllInitClasses@@YGXH@Z PROC				; DllInitClasses, COMDAT
; File c:\downloads\mediapoint\src\filters\baseclasses\dllentry.cpp
; Line 218
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	push	esi
	mov	DWORD PTR [ebp-8], -858993460		; ccccccccH
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
; Line 223
	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN4@DllInitCla
$LN3@DllInitCla:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN4@DllInitCla:
	mov	ecx, DWORD PTR _i$[ebp]
	cmp	ecx, DWORD PTR ?g_cTemplates@@3HA	; g_cTemplates
	jge	SHORT $LN5@DllInitCla
; Line 224
	mov	edx, DWORD PTR _i$[ebp]
	imul	edx, 20					; 00000014H
	add	edx, OFFSET ?g_Templates@@3PAVCFactoryTemplate@@A ; g_Templates
	mov	DWORD PTR _pT$82988[ebp], edx
; Line 225
	mov	eax, DWORD PTR _pT$82988[ebp]
	cmp	DWORD PTR [eax+12], 0
	je	SHORT $LN1@DllInitCla
; Line 226
	mov	esi, esp
	mov	ecx, DWORD PTR _pT$82988[ebp]
	mov	edx, DWORD PTR [ecx+4]
	push	edx
	mov	eax, DWORD PTR _bLoading$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pT$82988[ebp]
	mov	edx, DWORD PTR [ecx+12]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@DllInitCla:
; Line 228
	jmp	SHORT $LN3@DllInitCla
$LN5@DllInitCla:
; Line 230
	pop	esi
	add	esp, 8
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?DllInitClasses@@YGXH@Z ENDP				; DllInitClasses
_TEXT	ENDS
PUBLIC	?IsLocked@CClassFactory@@SGHXZ			; CClassFactory::IsLocked
PUBLIC	?ObjectsActive@CBaseObject@@SGJXZ		; CBaseObject::ObjectsActive
PUBLIC	_DllCanUnloadNow@0
EXTRN	?DbgLogInfo@@YAXKKPB_WZZ:PROC			; DbgLogInfo
; Function compile flags: /Odtp /RTCsu
;	COMDAT _DllCanUnloadNow@0
_TEXT	SEGMENT
_DllCanUnloadNow@0 PROC					; COMDAT
; Line 241
	push	ebp
	mov	ebp, esp
; Line 244
	call	?ObjectsActive@CBaseObject@@SGJXZ	; CBaseObject::ObjectsActive
	push	eax
	call	?IsLocked@CClassFactory@@SGHXZ		; CClassFactory::IsLocked
	push	eax
	push	OFFSET $SG82992
	push	2
	push	4
	call	?DbgLogInfo@@YAXKKPB_WZZ		; DbgLogInfo
	add	esp, 20					; 00000014H
; Line 246
	call	?IsLocked@CClassFactory@@SGHXZ		; CClassFactory::IsLocked
	test	eax, eax
	jne	SHORT $LN2@DllCanUnlo
	call	?ObjectsActive@CBaseObject@@SGJXZ	; CBaseObject::ObjectsActive
	test	eax, eax
	je	SHORT $LN3@DllCanUnlo
$LN2@DllCanUnlo:
; Line 247
	mov	eax, 1
	jmp	SHORT $LN4@DllCanUnlo
; Line 248
	jmp	SHORT $LN4@DllCanUnlo
$LN3@DllCanUnlo:
; Line 249
	xor	eax, eax
$LN4@DllCanUnlo:
; Line 251
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
_DllCanUnloadNow@0 ENDP
_TEXT	ENDS
EXTRN	?m_cObjects@CBaseObject@@0JA:DWORD		; CBaseObject::m_cObjects
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?ObjectsActive@CBaseObject@@SGJXZ
_TEXT	SEGMENT
?ObjectsActive@CBaseObject@@SGJXZ PROC			; CBaseObject::ObjectsActive, COMDAT
; File c:\downloads\mediapoint\src\filters\baseclasses\combase.h
; Line 190
	push	ebp
	mov	ebp, esp
; Line 191
	mov	eax, DWORD PTR ?m_cObjects@CBaseObject@@0JA ; CBaseObject::m_cObjects
; Line 192
	pop	ebp
	ret	0
?ObjectsActive@CBaseObject@@SGJXZ ENDP			; CBaseObject::ObjectsActive
; Function compile flags: /Odtp /RTCsu
_TEXT	ENDS
;	COMDAT ?IsLocked@CClassFactory@@SGHXZ
_TEXT	SEGMENT
?IsLocked@CClassFactory@@SGHXZ PROC			; CClassFactory::IsLocked, COMDAT
; File c:\downloads\mediapoint\src\filters\baseclasses\dllentry.cpp
; Line 58
	push	ebp
	mov	ebp, esp
; Line 59
	xor	eax, eax
	cmp	DWORD PTR ?m_cLocked@CClassFactory@@0HA, 0 ; CClassFactory::m_cLocked
	setg	al
; Line 60
	pop	ebp
	ret	0
?IsLocked@CClassFactory@@SGHXZ ENDP			; CClassFactory::IsLocked
_TEXT	ENDS
PUBLIC	?wcsrchr@@YAPA_WPA_W_W@Z			; wcsrchr
PUBLIC	__$ArrayPad$
PUBLIC	_DllEntryPoint@12
EXTRN	?DbgTerminate@@YGXXZ:PROC			; DbgTerminate
EXTRN	?DbgDumpObjectRegister@@YGXXZ:PROC		; DbgDumpObjectRegister
EXTRN	?m_ModuleName@@3PA_WA:BYTE			; m_ModuleName
EXTRN	__imp__wsprintfW:PROC
EXTRN	__imp__GetCurrentProcessId@0:PROC
EXTRN	__imp__GetCurrentThreadId@0:PROC
EXTRN	__imp__GetModuleFileNameW@12:PROC
EXTRN	?DbgSetModuleLevel@@YGXKK@Z:PROC		; DbgSetModuleLevel
EXTRN	__imp__GetVersionExW@4:PROC
EXTRN	?DbgInitialise@@YGXPAUHINSTANCE__@@@Z:PROC	; DbgInitialise
EXTRN	__imp__DisableThreadLibraryCalls@4:PROC
EXTRN	?g_fDbgInDllEntryPoint@@3_NA:BYTE		; g_fDbgInDllEntryPoint
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
; Function compile flags: /Odtp /RTCsu
;	COMDAT _DllEntryPoint@12
_TEXT	SEGMENT
tv64 = -1576						; size = 4
_cch$83024 = -1572					; size = 4
_pName$83021 = -1568					; size = 4
_FullName$83020 = -1560					; size = 520
_szInfo$83018 = -1032					; size = 1024
__$ArrayPad$ = -4					; size = 4
_hInstance$ = 8						; size = 4
_ulReason$ = 12						; size = 4
_pv$ = 16						; size = 4
_DllEntryPoint@12 PROC					; COMDAT
; Line 261
	push	ebp
	mov	ebp, esp
	sub	esp, 1576				; 00000628H
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-1576]
	mov	ecx, 394				; 0000018aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
; Line 264
	mov	BYTE PTR ?g_fDbgInDllEntryPoint@@3_NA, 1 ; g_fDbgInDllEntryPoint
; Line 267
	mov	eax, DWORD PTR _ulReason$[ebp]
	mov	DWORD PTR tv64[ebp], eax
	cmp	DWORD PTR tv64[ebp], 0
	je	$LN4@DllEntryPo
	cmp	DWORD PTR tv64[ebp], 1
	je	SHORT $LN7@DllEntryPo
	jmp	$LN8@DllEntryPo
$LN7@DllEntryPo:
; Line 271
	mov	esi, esp
	mov	ecx, DWORD PTR _hInstance$[ebp]
	push	ecx
	call	DWORD PTR __imp__DisableThreadLibraryCalls@4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 272
	mov	edx, DWORD PTR _hInstance$[ebp]
	push	edx
	call	?DbgInitialise@@YGXPAUHINSTANCE__@@@Z	; DbgInitialise
; Line 278
	mov	DWORD PTR ?g_amPlatform@@3KA, 1		; g_amPlatform
; Line 280
	mov	DWORD PTR ?g_osInfo@@3U_OSVERSIONINFOW@@A, 276 ; 00000114H
; Line 281
	mov	esi, esp
	push	OFFSET ?g_osInfo@@3U_OSVERSIONINFOW@@A	; g_osInfo
	call	DWORD PTR __imp__GetVersionExW@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	test	eax, eax
	je	SHORT $LN6@DllEntryPo
; Line 282
	mov	eax, DWORD PTR ?g_osInfo@@3U_OSVERSIONINFOW@@A+16
	mov	DWORD PTR ?g_amPlatform@@3KA, eax	; g_amPlatform
; Line 283
	jmp	SHORT $LN5@DllEntryPo
$LN6@DllEntryPo:
; Line 284
	push	OFFSET $SG83015
	push	1
	push	16					; 00000010H
	call	?DbgLogInfo@@YAXKKPB_WZZ		; DbgLogInfo
	add	esp, 12					; 0000000cH
$LN5@DllEntryPo:
; Line 288
	mov	ecx, DWORD PTR _hInstance$[ebp]
	mov	DWORD PTR ?g_hInst@@3PAUHINSTANCE__@@A, ecx ; g_hInst
; Line 289
	push	1
	call	?DllInitClasses@@YGXH@Z			; DllInitClasses
; Line 290
	jmp	$LN8@DllEntryPo
$LN4@DllEntryPo:
; Line 293
	push	0
	call	?DllInitClasses@@YGXH@Z			; DllInitClasses
; Line 296
	call	?ObjectsActive@CBaseObject@@SGJXZ	; CBaseObject::ObjectsActive
	test	eax, eax
	je	$LN3@DllEntryPo
; Line 297
	push	2
	push	4
	call	?DbgSetModuleLevel@@YGXKK@Z		; DbgSetModuleLevel
; Line 304
	mov	esi, esp
	push	260					; 00000104H
	lea	edx, DWORD PTR _FullName$83020[ebp]
	push	edx
	push	0
	call	DWORD PTR __imp__GetModuleFileNameW@12
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 305
	push	92					; 0000005cH
	lea	eax, DWORD PTR _FullName$83020[ebp]
	push	eax
	call	?wcsrchr@@YAPA_WPA_W_W@Z		; wcsrchr
	add	esp, 8
	mov	DWORD PTR _pName$83021[ebp], eax
; Line 306
	cmp	DWORD PTR _pName$83021[ebp], 0
	jne	SHORT $LN2@DllEntryPo
; Line 307
	lea	ecx, DWORD PTR _FullName$83020[ebp]
	mov	DWORD PTR _pName$83021[ebp], ecx
; Line 308
	jmp	SHORT $LN1@DllEntryPo
$LN2@DllEntryPo:
; Line 309
	mov	edx, DWORD PTR _pName$83021[ebp]
	add	edx, 2
	mov	DWORD PTR _pName$83021[ebp], edx
$LN1@DllEntryPo:
; Line 313
	mov	esi, esp
	call	DWORD PTR __imp__GetCurrentThreadId@0
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	mov	edi, esp
	call	DWORD PTR __imp__GetCurrentProcessId@0
	cmp	edi, esp
	call	__RTC_CheckEsp
	push	eax
	mov	eax, DWORD PTR _pName$83021[ebp]
	push	eax
	push	OFFSET $SG83025
	lea	ecx, DWORD PTR _szInfo$83018[ebp]
	push	ecx
	call	DWORD PTR __imp__wsprintfW
	add	esp, 20					; 00000014H
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _cch$83024[ebp], eax
; Line 316
	call	?ObjectsActive@CBaseObject@@SGJXZ	; CBaseObject::ObjectsActive
	mov	esi, esp
	push	eax
	push	OFFSET ?m_ModuleName@@3PA_WA		; m_ModuleName
	push	OFFSET $SG83026
	mov	edx, DWORD PTR _cch$83024[ebp]
	lea	eax, DWORD PTR _szInfo$83018[ebp+edx*2]
	push	eax
	call	DWORD PTR __imp__wsprintfW
	add	esp, 16					; 00000010H
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 317
	push	317					; 0000013dH
	push	OFFSET $SG83027
	lea	ecx, DWORD PTR _szInfo$83018[ebp]
	push	ecx
	call	?DbgAssert@@YGXPB_W0H@Z			; DbgAssert
; Line 321
	call	?DbgDumpObjectRegister@@YGXXZ		; DbgDumpObjectRegister
$LN3@DllEntryPo:
; Line 323
	call	?DbgTerminate@@YGXXZ			; DbgTerminate
$LN8@DllEntryPo:
; Line 329
	mov	BYTE PTR ?g_fDbgInDllEntryPoint@@3_NA, 0 ; g_fDbgInDllEntryPoint
; Line 331
	mov	eax, 1
; Line 332
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN15@DllEntryPo
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 1576				; 00000628H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
	npad	2
$LN15@DllEntryPo:
	DD	2
	DD	$LN14@DllEntryPo
$LN14@DllEntryPo:
	DD	-1032					; fffffbf8H
	DD	1024					; 00000400H
	DD	$LN12@DllEntryPo
	DD	-1560					; fffff9e8H
	DD	520					; 00000208H
	DD	$LN13@DllEntryPo
$LN13@DllEntryPo:
	DB	70					; 00000046H
	DB	117					; 00000075H
	DB	108					; 0000006cH
	DB	108					; 0000006cH
	DB	78					; 0000004eH
	DB	97					; 00000061H
	DB	109					; 0000006dH
	DB	101					; 00000065H
	DB	0
$LN12@DllEntryPo:
	DB	115					; 00000073H
	DB	122					; 0000007aH
	DB	73					; 00000049H
	DB	110					; 0000006eH
	DB	102					; 00000066H
	DB	111					; 0000006fH
	DB	0
_DllEntryPoint@12 ENDP
_TEXT	ENDS
EXTRN	_wcsrchr:PROC
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?wcsrchr@@YAPA_WPA_W_W@Z
_TEXT	SEGMENT
__Str$ = 8						; size = 4
__Ch$ = 12						; size = 2
?wcsrchr@@YAPA_WPA_W_W@Z PROC				; wcsrchr, COMDAT
; File c:\program files (x86)\microsoft visual studio 10.0\vc\include\string.h
; Line 366
	push	ebp
	mov	ebp, esp
	movzx	eax, WORD PTR __Ch$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Str$[ebp]
	push	ecx
	call	_wcsrchr
	add	esp, 8
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
?wcsrchr@@YAPA_WPA_W_W@Z ENDP				; wcsrchr
_TEXT	ENDS
END
